//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.22 at 08:27:36 PM UTC
//


package inteli.sudeste;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}alocacoesLoteTremSGDS"/&gt;
 *         &lt;element ref="{}analisesLoteSGDS"/&gt;
 *         &lt;element ref="{}analisesPilhasSGDS"/&gt;
 *         &lt;element ref="{}composicaoSolicitacaoPilhas"/&gt;
 *         &lt;element ref="{}composicoesPilha"/&gt;
 *         &lt;element ref="{}direcionamentosAlocacaoSGDS"/&gt;
 *         &lt;element ref="{}direcionamentosLoteSGDS"/&gt;
 *         &lt;element ref="{}listaMeritoDemerito"/&gt;
 *         &lt;element ref="{}listaMeritoDemeritoGrupo"/&gt;
 *         &lt;element ref="{}listaPlatts"/&gt;
 *         &lt;element ref="{}lotesSGDS"/&gt;
 *         &lt;element ref="{}movimentosEstoquePilhaSGDS"/&gt;
 *         &lt;element ref="{}movimentosPilhaPilhaSGDS"/&gt;
 *         &lt;element ref="{}movimentosPrevistoSGDS"/&gt;
 *         &lt;element ref="{}pilhas"/&gt;
 *         &lt;element ref="{}sobrasPilhasSGDS"/&gt;
 *         &lt;element ref="{}solicitacoesCarga"/&gt;
 *         &lt;element ref="{}solicitacoesProdutoSGDS"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alocacoesLoteTremSGDS",
    "analisesLoteSGDS",
    "analisesPilhasSGDS",
    "composicaoSolicitacaoPilhas",
    "composicoesPilha",
    "direcionamentosAlocacaoSGDS",
    "direcionamentosLoteSGDS",
    "listaMeritoDemerito",
    "listaMeritoDemeritoGrupo",
    "listaPlatts",
    "lotesSGDS",
    "movimentosEstoquePilhaSGDS",
    "movimentosPilhaPilhaSGDS",
    "movimentosPrevistoSGDS",
    "pilhas",
    "sobrasPilhasSGDS",
    "solicitacoesCarga",
    "solicitacoesProdutoSGDS"
})
@XmlRootElement(name = "apoio")
public class Apoio {

    @XmlElement(required = true)
    protected AlocacoesLoteTremSGDS alocacoesLoteTremSGDS;
    @XmlElement(required = true)
    protected AnalisesLoteSGDS analisesLoteSGDS;
    @XmlElement(required = true)
    protected AnalisesPilhasSGDS analisesPilhasSGDS;
    @XmlElement(required = true)
    protected ComposicaoSolicitacaoPilhas composicaoSolicitacaoPilhas;
    @XmlElement(required = true)
    protected ComposicoesPilha composicoesPilha;
    @XmlElement(required = true)
    protected DirecionamentosAlocacaoSGDS direcionamentosAlocacaoSGDS;
    @XmlElement(required = true)
    protected DirecionamentosLoteSGDS direcionamentosLoteSGDS;
    @XmlElement(required = true)
    protected ListaMeritoDemerito listaMeritoDemerito;
    @XmlElement(required = true)
    protected ListaMeritoDemeritoGrupo listaMeritoDemeritoGrupo;
    @XmlElement(required = true)
    protected ListaPlatts listaPlatts;
    @XmlElement(required = true)
    protected LotesSGDS lotesSGDS;
    @XmlElement(required = true)
    protected MovimentosEstoquePilhaSGDS movimentosEstoquePilhaSGDS;
    @XmlElement(required = true)
    protected MovimentosPilhaPilhaSGDS movimentosPilhaPilhaSGDS;
    @XmlElement(required = true)
    protected MovimentosPrevistoSGDS movimentosPrevistoSGDS;
    @XmlElement(required = true)
    protected Pilhas pilhas;
    @XmlElement(required = true)
    protected SobrasPilhasSGDS sobrasPilhasSGDS;
    @XmlElement(required = true)
    protected SolicitacoesCarga solicitacoesCarga;
    @XmlElement(required = true)
    protected SolicitacoesProdutoSGDS solicitacoesProdutoSGDS;

    /**
     * Gets the value of the alocacoesLoteTremSGDS property.
     *
     * @return
     *     possible object is
     *     {@link AlocacoesLoteTremSGDS }
     *
     */
    public AlocacoesLoteTremSGDS getAlocacoesLoteTremSGDS() {
        return alocacoesLoteTremSGDS;
    }

    /**
     * Sets the value of the alocacoesLoteTremSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link AlocacoesLoteTremSGDS }
     *
     */
    public void setAlocacoesLoteTremSGDS(AlocacoesLoteTremSGDS value) {
        this.alocacoesLoteTremSGDS = value;
    }

    /**
     * Gets the value of the analisesLoteSGDS property.
     *
     * @return
     *     possible object is
     *     {@link AnalisesLoteSGDS }
     *
     */
    public AnalisesLoteSGDS getAnalisesLoteSGDS() {
        return analisesLoteSGDS;
    }

    /**
     * Sets the value of the analisesLoteSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link AnalisesLoteSGDS }
     *
     */
    public void setAnalisesLoteSGDS(AnalisesLoteSGDS value) {
        this.analisesLoteSGDS = value;
    }

    /**
     * Gets the value of the analisesPilhasSGDS property.
     *
     * @return
     *     possible object is
     *     {@link AnalisesPilhasSGDS }
     *
     */
    public AnalisesPilhasSGDS getAnalisesPilhasSGDS() {
        return analisesPilhasSGDS;
    }

    /**
     * Sets the value of the analisesPilhasSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link AnalisesPilhasSGDS }
     *
     */
    public void setAnalisesPilhasSGDS(AnalisesPilhasSGDS value) {
        this.analisesPilhasSGDS = value;
    }

    /**
     * Gets the value of the composicaoSolicitacaoPilhas property.
     *
     * @return
     *     possible object is
     *     {@link ComposicaoSolicitacaoPilhas }
     *
     */
    public ComposicaoSolicitacaoPilhas getComposicaoSolicitacaoPilhas() {
        return composicaoSolicitacaoPilhas;
    }

    /**
     * Sets the value of the composicaoSolicitacaoPilhas property.
     *
     * @param value
     *     allowed object is
     *     {@link ComposicaoSolicitacaoPilhas }
     *
     */
    public void setComposicaoSolicitacaoPilhas(ComposicaoSolicitacaoPilhas value) {
        this.composicaoSolicitacaoPilhas = value;
    }

    /**
     * Gets the value of the composicoesPilha property.
     *
     * @return
     *     possible object is
     *     {@link ComposicoesPilha }
     *
     */
    public ComposicoesPilha getComposicoesPilha() {
        return composicoesPilha;
    }

    /**
     * Sets the value of the composicoesPilha property.
     *
     * @param value
     *     allowed object is
     *     {@link ComposicoesPilha }
     *
     */
    public void setComposicoesPilha(ComposicoesPilha value) {
        this.composicoesPilha = value;
    }

    /**
     * Gets the value of the direcionamentosAlocacaoSGDS property.
     *
     * @return
     *     possible object is
     *     {@link DirecionamentosAlocacaoSGDS }
     *
     */
    public DirecionamentosAlocacaoSGDS getDirecionamentosAlocacaoSGDS() {
        return direcionamentosAlocacaoSGDS;
    }

    /**
     * Sets the value of the direcionamentosAlocacaoSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link DirecionamentosAlocacaoSGDS }
     *
     */
    public void setDirecionamentosAlocacaoSGDS(DirecionamentosAlocacaoSGDS value) {
        this.direcionamentosAlocacaoSGDS = value;
    }

    /**
     * Gets the value of the direcionamentosLoteSGDS property.
     *
     * @return
     *     possible object is
     *     {@link DirecionamentosLoteSGDS }
     *
     */
    public DirecionamentosLoteSGDS getDirecionamentosLoteSGDS() {
        return direcionamentosLoteSGDS;
    }

    /**
     * Sets the value of the direcionamentosLoteSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link DirecionamentosLoteSGDS }
     *
     */
    public void setDirecionamentosLoteSGDS(DirecionamentosLoteSGDS value) {
        this.direcionamentosLoteSGDS = value;
    }

    /**
     * Gets the value of the listaMeritoDemerito property.
     *
     * @return
     *     possible object is
     *     {@link ListaMeritoDemerito }
     *
     */
    public ListaMeritoDemerito getListaMeritoDemerito() {
        return listaMeritoDemerito;
    }

    /**
     * Sets the value of the listaMeritoDemerito property.
     *
     * @param value
     *     allowed object is
     *     {@link ListaMeritoDemerito }
     *
     */
    public void setListaMeritoDemerito(ListaMeritoDemerito value) {
        this.listaMeritoDemerito = value;
    }

    /**
     * Gets the value of the listaMeritoDemeritoGrupo property.
     *
     * @return
     *     possible object is
     *     {@link ListaMeritoDemeritoGrupo }
     *
     */
    public ListaMeritoDemeritoGrupo getListaMeritoDemeritoGrupo() {
        return listaMeritoDemeritoGrupo;
    }

    /**
     * Sets the value of the listaMeritoDemeritoGrupo property.
     *
     * @param value
     *     allowed object is
     *     {@link ListaMeritoDemeritoGrupo }
     *
     */
    public void setListaMeritoDemeritoGrupo(ListaMeritoDemeritoGrupo value) {
        this.listaMeritoDemeritoGrupo = value;
    }

    /**
     * Gets the value of the listaPlatts property.
     *
     * @return
     *     possible object is
     *     {@link ListaPlatts }
     *
     */
    public ListaPlatts getListaPlatts() {
        return listaPlatts;
    }

    /**
     * Sets the value of the listaPlatts property.
     *
     * @param value
     *     allowed object is
     *     {@link ListaPlatts }
     *
     */
    public void setListaPlatts(ListaPlatts value) {
        this.listaPlatts = value;
    }

    /**
     * Gets the value of the lotesSGDS property.
     *
     * @return
     *     possible object is
     *     {@link LotesSGDS }
     *
     */
    public LotesSGDS getLotesSGDS() {
        return lotesSGDS;
    }

    /**
     * Sets the value of the lotesSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link LotesSGDS }
     *
     */
    public void setLotesSGDS(LotesSGDS value) {
        this.lotesSGDS = value;
    }

    /**
     * Gets the value of the movimentosEstoquePilhaSGDS property.
     *
     * @return
     *     possible object is
     *     {@link MovimentosEstoquePilhaSGDS }
     *
     */
    public MovimentosEstoquePilhaSGDS getMovimentosEstoquePilhaSGDS() {
        return movimentosEstoquePilhaSGDS;
    }

    /**
     * Sets the value of the movimentosEstoquePilhaSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link MovimentosEstoquePilhaSGDS }
     *
     */
    public void setMovimentosEstoquePilhaSGDS(MovimentosEstoquePilhaSGDS value) {
        this.movimentosEstoquePilhaSGDS = value;
    }

    /**
     * Gets the value of the movimentosPilhaPilhaSGDS property.
     *
     * @return
     *     possible object is
     *     {@link MovimentosPilhaPilhaSGDS }
     *
     */
    public MovimentosPilhaPilhaSGDS getMovimentosPilhaPilhaSGDS() {
        return movimentosPilhaPilhaSGDS;
    }

    /**
     * Sets the value of the movimentosPilhaPilhaSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link MovimentosPilhaPilhaSGDS }
     *
     */
    public void setMovimentosPilhaPilhaSGDS(MovimentosPilhaPilhaSGDS value) {
        this.movimentosPilhaPilhaSGDS = value;
    }

    /**
     * Gets the value of the movimentosPrevistoSGDS property.
     *
     * @return
     *     possible object is
     *     {@link MovimentosPrevistoSGDS }
     *
     */
    public MovimentosPrevistoSGDS getMovimentosPrevistoSGDS() {
        return movimentosPrevistoSGDS;
    }

    /**
     * Sets the value of the movimentosPrevistoSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link MovimentosPrevistoSGDS }
     *
     */
    public void setMovimentosPrevistoSGDS(MovimentosPrevistoSGDS value) {
        this.movimentosPrevistoSGDS = value;
    }

    /**
     * Gets the value of the pilhas property.
     *
     * @return
     *     possible object is
     *     {@link Pilhas }
     *
     */
    public Pilhas getPilhas() {
        return pilhas;
    }

    /**
     * Sets the value of the pilhas property.
     *
     * @param value
     *     allowed object is
     *     {@link Pilhas }
     *
     */
    public void setPilhas(Pilhas value) {
        this.pilhas = value;
    }

    /**
     * Gets the value of the sobrasPilhasSGDS property.
     *
     * @return
     *     possible object is
     *     {@link SobrasPilhasSGDS }
     *
     */
    public SobrasPilhasSGDS getSobrasPilhasSGDS() {
        return sobrasPilhasSGDS;
    }

    /**
     * Sets the value of the sobrasPilhasSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link SobrasPilhasSGDS }
     *
     */
    public void setSobrasPilhasSGDS(SobrasPilhasSGDS value) {
        this.sobrasPilhasSGDS = value;
    }

    /**
     * Gets the value of the solicitacoesCarga property.
     *
     * @return
     *     possible object is
     *     {@link SolicitacoesCarga }
     *
     */
    public SolicitacoesCarga getSolicitacoesCarga() {
        return solicitacoesCarga;
    }

    /**
     * Sets the value of the solicitacoesCarga property.
     *
     * @param value
     *     allowed object is
     *     {@link SolicitacoesCarga }
     *
     */
    public void setSolicitacoesCarga(SolicitacoesCarga value) {
        this.solicitacoesCarga = value;
    }

    /**
     * Gets the value of the solicitacoesProdutoSGDS property.
     *
     * @return
     *     possible object is
     *     {@link SolicitacoesProdutoSGDS }
     *
     */
    public SolicitacoesProdutoSGDS getSolicitacoesProdutoSGDS() {
        return solicitacoesProdutoSGDS;
    }

    /**
     * Sets the value of the solicitacoesProdutoSGDS property.
     *
     * @param value
     *     allowed object is
     *     {@link SolicitacoesProdutoSGDS }
     *
     */
    public void setSolicitacoesProdutoSGDS(SolicitacoesProdutoSGDS value) {
        this.solicitacoesProdutoSGDS = value;
    }

}
