//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 08:27:36 PM UTC 
//


package inteli.sudeste;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}codigoProduto"/&gt;
 *         &lt;element ref="{}dataInicio"/&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}indicadorTipoRegra"/&gt;
 *         &lt;element ref="{}regrasBlendagemProduto" minOccurs="0"/&gt;
 *         &lt;element ref="{}visao"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoProduto",
    "dataInicio",
    "id",
    "indicadorTipoRegra",
    "regrasBlendagemProduto",
    "visao"
})
@XmlRootElement(name = "blendagemProduto")
public class BlendagemProduto {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoProduto;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataInicio;
    @XmlElement(required = true)
    protected Id id;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String indicadorTipoRegra;
    protected RegrasBlendagemProduto regrasBlendagemProduto;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String visao;

    /**
     * Gets the value of the codigoProduto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoProduto() {
        return codigoProduto;
    }

    /**
     * Sets the value of the codigoProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoProduto(String value) {
        this.codigoProduto = value;
    }

    /**
     * Gets the value of the dataInicio property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataInicio() {
        return dataInicio;
    }

    /**
     * Sets the value of the dataInicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataInicio(XMLGregorianCalendar value) {
        this.dataInicio = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the indicadorTipoRegra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorTipoRegra() {
        return indicadorTipoRegra;
    }

    /**
     * Sets the value of the indicadorTipoRegra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorTipoRegra(String value) {
        this.indicadorTipoRegra = value;
    }

    /**
     * Gets the value of the regrasBlendagemProduto property.
     * 
     * @return
     *     possible object is
     *     {@link RegrasBlendagemProduto }
     *     
     */
    public RegrasBlendagemProduto getRegrasBlendagemProduto() {
        return regrasBlendagemProduto;
    }

    /**
     * Sets the value of the regrasBlendagemProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegrasBlendagemProduto }
     *     
     */
    public void setRegrasBlendagemProduto(RegrasBlendagemProduto value) {
        this.regrasBlendagemProduto = value;
    }

    /**
     * Gets the value of the visao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisao() {
        return visao;
    }

    /**
     * Sets the value of the visao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisao(String value) {
        this.visao = value;
    }

}
