//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 08:27:36 PM UTC 
//


package inteli.sudeste;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ajustesLogistica"/&gt;
 *         &lt;element ref="{}arranjosProducao"/&gt;
 *         &lt;element ref="{}cadeiasEstendida"/&gt;
 *         &lt;element ref="{}capacidadesEstocagemMaxMin"/&gt;
 *         &lt;element ref="{}capacidadesBlendagem"/&gt;
 *         &lt;element ref="{}capacidadesMaxSobraLotes"/&gt;
 *         &lt;element ref="{}capacidadesProducaoDisponibilizacaoElo"/&gt;
 *         &lt;element ref="{}capacidadesProducaoDisponibilizacaoProdutoElo"/&gt;
 *         &lt;element ref="{}capacidadesProducaoDisponibilizacaoProdutoHoraria"/&gt;
 *         &lt;element ref="{}categoriasVendaAPS"/&gt;
 *         &lt;element ref="{}classificacaoCompany"/&gt;
 *         &lt;element ref="{}clientesAPS"/&gt;
 *         &lt;element ref="{}complexosProdutivosAPS"/&gt;
 *         &lt;element ref="{}contratosTerceirosElo"/&gt;
 *         &lt;element ref="{}contratosTerceirosEmpresaTransporte"/&gt;
 *         &lt;element ref="{}custosMina"/&gt;
 *         &lt;element ref="{}custosPatio"/&gt;
 *         &lt;element ref="{}custosPorto"/&gt;
 *         &lt;element ref="{}custosSite"/&gt;
 *         &lt;element ref="{}custosUsinaBeneficiamento"/&gt;
 *         &lt;element ref="{}custosUsinaBriquete"/&gt;
 *         &lt;element ref="{}custosUsinaPelotizacao"/&gt;
 *         &lt;element ref="{}custosUsinaTransformacao"/&gt;
 *         &lt;element ref="{}custosUtilizacaoEstoqueInicialPorSite"/&gt;
 *         &lt;element ref="{}custosBlendagemPorto"/&gt;
 *         &lt;element ref="{}CustosEloCategoriaProduto"/&gt;
 *         &lt;element ref="{}custosFerrovia"/&gt;
 *         &lt;element ref="{}custosTrechoCategoriaProduto"/&gt;
 *         &lt;element ref="{}descontos"/&gt;
 *         &lt;element ref="{}desembaracos"/&gt;
 *         &lt;element ref="{}disponibilidadesAPS"/&gt;
 *         &lt;element ref="{}disponibilidadesCompatibilidadeDetalheAPS"/&gt;
 *         &lt;element ref="{}disponibilidadesDetalheAPS"/&gt;
 *         &lt;element ref="{}disponibilidadesEstoqueInicial"/&gt;
 *         &lt;element ref="{}distribuicoesMensaisCadeia"/&gt;
 *         &lt;element ref="{}escritoriosAPS"/&gt;
 *         &lt;element ref="{}estoquesEstrategicos"/&gt;
 *         &lt;element ref="{}estoquesIniciais"/&gt;
 *         &lt;element ref="{}expedicoesMinimas"/&gt;
 *         &lt;element ref="{}faixaCustoFreteAdicionalList"/&gt;
 *         &lt;element ref="{}faixaCustoFreteAdicionalTrechos"/&gt;
 *         &lt;element ref="{}faixasEqualizacaoQualidade"/&gt;
 *         &lt;element ref="{}faixasCustoFreteAdicionalList"/&gt;
 *         &lt;element ref="{}finosDePelota"/&gt;
 *         &lt;element ref="{}fornecedoresAPS"/&gt;
 *         &lt;element ref="{}grupoClienteAPS"/&gt;
 *         &lt;element ref="{}grupoPorto"/&gt;
 *         &lt;element ref="{}gruposProdutosExclusivos"/&gt;
 *         &lt;element ref="{}historicoAssociacoesElo"/&gt;
 *         &lt;element ref="{}indicesReferencia"/&gt;
 *         &lt;element ref="{}instalacoesUsinaBeneficiamento"/&gt;
 *         &lt;element ref="{}layDayTamanhosEmbarque"/&gt;
 *         &lt;element ref="{}limitesProducaoDisponibilizacaoElo"/&gt;
 *         &lt;element ref="{}limitesProducaoDisponibilizacaoProdutoElo"/&gt;
 *         &lt;element ref="{}manutencoesElo"/&gt;
 *         &lt;element ref="{}minasAPS"/&gt;
 *         &lt;element ref="{}multasBonificacaoContratoTransporte"/&gt;
 *         &lt;element ref="{}parametrosCorporativos"/&gt;
 *         &lt;element ref="{}parametrosEqualizacaoQualidade"/&gt;
 *         &lt;element ref="{}patiosAPS"/&gt;
 *         &lt;element ref="{}peneiramentosAPS"/&gt;
 *         &lt;element ref="{}percentuaisAtendimentoTrimestreAPS"/&gt;
 *         &lt;element ref="{}pilhasPadrao"/&gt;
 *         &lt;element ref="{}planejamentosEmbarques"/&gt;
 *         &lt;element ref="{}planosContratacaoAPS"/&gt;
 *         &lt;element ref="{}planosContratacaoDetalheAPS"/&gt;
 *         &lt;element ref="{}pontosCargaDescargaAPS"/&gt;
 *         &lt;element ref="{}portosAPS"/&gt;
 *         &lt;element ref="{}previsoesCargaCaminhaoAsia"/&gt;
 *         &lt;element ref="{}previsoesCargaNavio"/&gt;
 *         &lt;element ref="{}prioridadesPlanoAPS"/&gt;
 *         &lt;element ref="{}processosImportacaoAsia"/&gt;
 *         &lt;element ref="{}produtosArranjo"/&gt;
 *         &lt;element ref="{}produtosExclusivosArranjo"/&gt;
 *         &lt;element ref="{}qualidadesProdutoElo"/&gt;
 *         &lt;element ref="{}receitasCusto"/&gt;
 *         &lt;element ref="{}recuperacoesMassaAsia"/&gt;
 *         &lt;element ref="{}regioesAPS"/&gt;
 *         &lt;element ref="{}regrasTransformacaoUsina"/&gt;
 *         &lt;element ref="{}regrasTransformacaoUsinaPelotizacao"/&gt;
 *         &lt;element ref="{}sistemasProducaoAPS"/&gt;
 *         &lt;element ref="{}sitesProdutivosAPS"/&gt;
 *         &lt;element ref="{}splitsInstalacaoAPS"/&gt;
 *         &lt;element ref="{}taxasDescargaExpedicaoElo"/&gt;
 *         &lt;element ref="{}tiposNavios"/&gt;
 *         &lt;element ref="{}tiposPrecificacoesCliente"/&gt;
 *         &lt;element ref="{}trechosContratoTerceiroTransporte"/&gt;
 *         &lt;element ref="{}usinasAsia"/&gt;
 *         &lt;element ref="{}usinasBeneficiamentoAPS"/&gt;
 *         &lt;element ref="{}usinasBriqueteAPS"/&gt;
 *         &lt;element ref="{}usinasPelotizacaoAPS"/&gt;
 *         &lt;element ref="{}usinasTransformacaoAPS"/&gt;
 *         &lt;element ref="{}utilizacoesEstoqueInicial"/&gt;
 *         &lt;element ref="{}utilizacoesProgramadasInstalacao"/&gt;
 *         &lt;element ref="{}validadesEstoque"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ajustesLogistica",
    "arranjosProducao",
    "cadeiasEstendida",
    "capacidadesEstocagemMaxMin",
    "capacidadesBlendagem",
    "capacidadesMaxSobraLotes",
    "capacidadesProducaoDisponibilizacaoElo",
    "capacidadesProducaoDisponibilizacaoProdutoElo",
    "capacidadesProducaoDisponibilizacaoProdutoHoraria",
    "categoriasVendaAPS",
    "classificacaoCompany",
    "clientesAPS",
    "complexosProdutivosAPS",
    "contratosTerceirosElo",
    "contratosTerceirosEmpresaTransporte",
    "custosMina",
    "custosPatio",
    "custosPorto",
    "custosSite",
    "custosUsinaBeneficiamento",
    "custosUsinaBriquete",
    "custosUsinaPelotizacao",
    "custosUsinaTransformacao",
    "custosUtilizacaoEstoqueInicialPorSite",
    "custosBlendagemPorto",
    "custosEloCategoriaProduto",
    "custosFerrovia",
    "custosTrechoCategoriaProduto",
    "descontos",
    "desembaracos",
    "disponibilidadesAPS",
    "disponibilidadesCompatibilidadeDetalheAPS",
    "disponibilidadesDetalheAPS",
    "disponibilidadesEstoqueInicial",
    "distribuicoesMensaisCadeia",
    "escritoriosAPS",
    "estoquesEstrategicos",
    "estoquesIniciais",
    "expedicoesMinimas",
    "faixaCustoFreteAdicionalList",
    "faixaCustoFreteAdicionalTrechos",
    "faixasEqualizacaoQualidade",
    "faixasCustoFreteAdicionalList",
    "finosDePelota",
    "fornecedoresAPS",
    "grupoClienteAPS",
    "grupoPorto",
    "gruposProdutosExclusivos",
    "historicoAssociacoesElo",
    "indicesReferencia",
    "instalacoesUsinaBeneficiamento",
    "layDayTamanhosEmbarque",
    "limitesProducaoDisponibilizacaoElo",
    "limitesProducaoDisponibilizacaoProdutoElo",
    "manutencoesElo",
    "minasAPS",
    "multasBonificacaoContratoTransporte",
    "parametrosCorporativos",
    "parametrosEqualizacaoQualidade",
    "patiosAPS",
    "peneiramentosAPS",
    "percentuaisAtendimentoTrimestreAPS",
    "pilhasPadrao",
    "planejamentosEmbarques",
    "planosContratacaoAPS",
    "planosContratacaoDetalheAPS",
    "pontosCargaDescargaAPS",
    "portosAPS",
    "previsoesCargaCaminhaoAsia",
    "previsoesCargaNavio",
    "prioridadesPlanoAPS",
    "processosImportacaoAsia",
    "produtosArranjo",
    "produtosExclusivosArranjo",
    "qualidadesProdutoElo",
    "receitasCusto",
    "recuperacoesMassaAsia",
    "regioesAPS",
    "regrasTransformacaoUsina",
    "regrasTransformacaoUsinaPelotizacao",
    "sistemasProducaoAPS",
    "sitesProdutivosAPS",
    "splitsInstalacaoAPS",
    "taxasDescargaExpedicaoElo",
    "tiposNavios",
    "tiposPrecificacoesCliente",
    "trechosContratoTerceiroTransporte",
    "usinasAsia",
    "usinasBeneficiamentoAPS",
    "usinasBriqueteAPS",
    "usinasPelotizacaoAPS",
    "usinasTransformacaoAPS",
    "utilizacoesEstoqueInicial",
    "utilizacoesProgramadasInstalacao",
    "validadesEstoque"
})
@XmlRootElement(name = "cadeia")
public class Cadeia {

    @XmlElement(required = true)
    protected AjustesLogistica ajustesLogistica;
    @XmlElement(required = true)
    protected ArranjosProducao arranjosProducao;
    @XmlElement(required = true)
    protected CadeiasEstendida cadeiasEstendida;
    @XmlElement(required = true)
    protected CapacidadesEstocagemMaxMin capacidadesEstocagemMaxMin;
    @XmlElement(required = true)
    protected CapacidadesBlendagem capacidadesBlendagem;
    @XmlElement(required = true)
    protected CapacidadesMaxSobraLotes capacidadesMaxSobraLotes;
    @XmlElement(required = true)
    protected CapacidadesProducaoDisponibilizacaoElo capacidadesProducaoDisponibilizacaoElo;
    @XmlElement(required = true)
    protected CapacidadesProducaoDisponibilizacaoProdutoElo capacidadesProducaoDisponibilizacaoProdutoElo;
    @XmlElement(required = true)
    protected CapacidadesProducaoDisponibilizacaoProdutoHoraria capacidadesProducaoDisponibilizacaoProdutoHoraria;
    @XmlElement(required = true)
    protected CategoriasVendaAPS categoriasVendaAPS;
    @XmlElement(required = true)
    protected ClassificacaoCompany classificacaoCompany;
    @XmlElement(required = true)
    protected ClientesAPS clientesAPS;
    @XmlElement(required = true)
    protected ComplexosProdutivosAPS complexosProdutivosAPS;
    @XmlElement(required = true)
    protected ContratosTerceirosElo contratosTerceirosElo;
    @XmlElement(required = true)
    protected ContratosTerceirosEmpresaTransporte contratosTerceirosEmpresaTransporte;
    @XmlElement(required = true)
    protected CustosMina custosMina;
    @XmlElement(required = true)
    protected CustosPatio custosPatio;
    @XmlElement(required = true)
    protected CustosPorto custosPorto;
    @XmlElement(required = true)
    protected CustosSite custosSite;
    @XmlElement(required = true)
    protected CustosUsinaBeneficiamento custosUsinaBeneficiamento;
    @XmlElement(required = true)
    protected CustosUsinaBriquete custosUsinaBriquete;
    @XmlElement(required = true)
    protected CustosUsinaPelotizacao custosUsinaPelotizacao;
    @XmlElement(required = true)
    protected CustosUsinaTransformacao custosUsinaTransformacao;
    @XmlElement(required = true)
    protected CustosUtilizacaoEstoqueInicialPorSite custosUtilizacaoEstoqueInicialPorSite;
    @XmlElement(required = true)
    protected CustosBlendagemPorto custosBlendagemPorto;
    @XmlElement(name = "CustosEloCategoriaProduto", required = true)
    protected CustosEloCategoriaProduto custosEloCategoriaProduto;
    @XmlElement(required = true)
    protected CustosFerrovia custosFerrovia;
    @XmlElement(required = true)
    protected CustosTrechoCategoriaProduto custosTrechoCategoriaProduto;
    @XmlElement(required = true)
    protected Descontos descontos;
    @XmlElement(required = true)
    protected Desembaracos desembaracos;
    @XmlElement(required = true)
    protected DisponibilidadesAPS disponibilidadesAPS;
    @XmlElement(required = true)
    protected DisponibilidadesCompatibilidadeDetalheAPS disponibilidadesCompatibilidadeDetalheAPS;
    @XmlElement(required = true)
    protected DisponibilidadesDetalheAPS disponibilidadesDetalheAPS;
    @XmlElement(required = true)
    protected DisponibilidadesEstoqueInicial disponibilidadesEstoqueInicial;
    @XmlElement(required = true)
    protected DistribuicoesMensaisCadeia distribuicoesMensaisCadeia;
    @XmlElement(required = true)
    protected EscritoriosAPS escritoriosAPS;
    @XmlElement(required = true)
    protected EstoquesEstrategicos estoquesEstrategicos;
    @XmlElement(required = true)
    protected EstoquesIniciais estoquesIniciais;
    @XmlElement(required = true)
    protected ExpedicoesMinimas expedicoesMinimas;
    @XmlElement(required = true)
    protected FaixaCustoFreteAdicionalList faixaCustoFreteAdicionalList;
    @XmlElement(required = true)
    protected FaixaCustoFreteAdicionalTrechos faixaCustoFreteAdicionalTrechos;
    @XmlElement(required = true)
    protected FaixasEqualizacaoQualidade faixasEqualizacaoQualidade;
    @XmlElement(required = true)
    protected FaixasCustoFreteAdicionalList faixasCustoFreteAdicionalList;
    @XmlElement(required = true)
    protected FinosDePelota finosDePelota;
    @XmlElement(required = true)
    protected FornecedoresAPS fornecedoresAPS;
    @XmlElement(required = true)
    protected GrupoClienteAPS grupoClienteAPS;
    @XmlElement(required = true)
    protected GrupoPorto grupoPorto;
    @XmlElement(required = true)
    protected GruposProdutosExclusivos gruposProdutosExclusivos;
    @XmlElement(required = true)
    protected HistoricoAssociacoesElo historicoAssociacoesElo;
    @XmlElement(required = true)
    protected IndicesReferencia indicesReferencia;
    @XmlElement(required = true)
    protected InstalacoesUsinaBeneficiamento instalacoesUsinaBeneficiamento;
    @XmlElement(required = true)
    protected LayDayTamanhosEmbarque layDayTamanhosEmbarque;
    @XmlElement(required = true)
    protected LimitesProducaoDisponibilizacaoElo limitesProducaoDisponibilizacaoElo;
    @XmlElement(required = true)
    protected LimitesProducaoDisponibilizacaoProdutoElo limitesProducaoDisponibilizacaoProdutoElo;
    @XmlElement(required = true)
    protected ManutencoesElo manutencoesElo;
    @XmlElement(required = true)
    protected MinasAPS minasAPS;
    @XmlElement(required = true)
    protected MultasBonificacaoContratoTransporte multasBonificacaoContratoTransporte;
    @XmlElement(required = true)
    protected ParametrosCorporativos parametrosCorporativos;
    @XmlElement(required = true)
    protected ParametrosEqualizacaoQualidade parametrosEqualizacaoQualidade;
    @XmlElement(required = true)
    protected PatiosAPS patiosAPS;
    @XmlElement(required = true)
    protected PeneiramentosAPS peneiramentosAPS;
    @XmlElement(required = true)
    protected PercentuaisAtendimentoTrimestreAPS percentuaisAtendimentoTrimestreAPS;
    @XmlElement(required = true)
    protected PilhasPadrao pilhasPadrao;
    @XmlElement(required = true)
    protected PlanejamentosEmbarques planejamentosEmbarques;
    @XmlElement(required = true)
    protected PlanosContratacaoAPS planosContratacaoAPS;
    @XmlElement(required = true)
    protected PlanosContratacaoDetalheAPS planosContratacaoDetalheAPS;
    @XmlElement(required = true)
    protected PontosCargaDescargaAPS pontosCargaDescargaAPS;
    @XmlElement(required = true)
    protected PortosAPS portosAPS;
    @XmlElement(required = true)
    protected PrevisoesCargaCaminhaoAsia previsoesCargaCaminhaoAsia;
    @XmlElement(required = true)
    protected PrevisoesCargaNavio previsoesCargaNavio;
    @XmlElement(required = true)
    protected PrioridadesPlanoAPS prioridadesPlanoAPS;
    @XmlElement(required = true)
    protected ProcessosImportacaoAsia processosImportacaoAsia;
    @XmlElement(required = true)
    protected ProdutosArranjo produtosArranjo;
    @XmlElement(required = true)
    protected ProdutosExclusivosArranjo produtosExclusivosArranjo;
    @XmlElement(required = true)
    protected QualidadesProdutoElo qualidadesProdutoElo;
    @XmlElement(required = true)
    protected ReceitasCusto receitasCusto;
    @XmlElement(required = true)
    protected RecuperacoesMassaAsia recuperacoesMassaAsia;
    @XmlElement(required = true)
    protected RegioesAPS regioesAPS;
    @XmlElement(required = true)
    protected RegrasTransformacaoUsina regrasTransformacaoUsina;
    @XmlElement(required = true)
    protected RegrasTransformacaoUsinaPelotizacao regrasTransformacaoUsinaPelotizacao;
    @XmlElement(required = true)
    protected SistemasProducaoAPS sistemasProducaoAPS;
    @XmlElement(required = true)
    protected SitesProdutivosAPS sitesProdutivosAPS;
    @XmlElement(required = true)
    protected SplitsInstalacaoAPS splitsInstalacaoAPS;
    @XmlElement(required = true)
    protected TaxasDescargaExpedicaoElo taxasDescargaExpedicaoElo;
    @XmlElement(required = true)
    protected TiposNavios tiposNavios;
    @XmlElement(required = true)
    protected TiposPrecificacoesCliente tiposPrecificacoesCliente;
    @XmlElement(required = true)
    protected TrechosContratoTerceiroTransporte trechosContratoTerceiroTransporte;
    @XmlElement(required = true)
    protected UsinasAsia usinasAsia;
    @XmlElement(required = true)
    protected UsinasBeneficiamentoAPS usinasBeneficiamentoAPS;
    @XmlElement(required = true)
    protected UsinasBriqueteAPS usinasBriqueteAPS;
    @XmlElement(required = true)
    protected UsinasPelotizacaoAPS usinasPelotizacaoAPS;
    @XmlElement(required = true)
    protected UsinasTransformacaoAPS usinasTransformacaoAPS;
    @XmlElement(required = true)
    protected UtilizacoesEstoqueInicial utilizacoesEstoqueInicial;
    @XmlElement(required = true)
    protected UtilizacoesProgramadasInstalacao utilizacoesProgramadasInstalacao;
    @XmlElement(required = true)
    protected ValidadesEstoque validadesEstoque;

    /**
     * Gets the value of the ajustesLogistica property.
     * 
     * @return
     *     possible object is
     *     {@link AjustesLogistica }
     *     
     */
    public AjustesLogistica getAjustesLogistica() {
        return ajustesLogistica;
    }

    /**
     * Sets the value of the ajustesLogistica property.
     * 
     * @param value
     *     allowed object is
     *     {@link AjustesLogistica }
     *     
     */
    public void setAjustesLogistica(AjustesLogistica value) {
        this.ajustesLogistica = value;
    }

    /**
     * Gets the value of the arranjosProducao property.
     * 
     * @return
     *     possible object is
     *     {@link ArranjosProducao }
     *     
     */
    public ArranjosProducao getArranjosProducao() {
        return arranjosProducao;
    }

    /**
     * Sets the value of the arranjosProducao property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArranjosProducao }
     *     
     */
    public void setArranjosProducao(ArranjosProducao value) {
        this.arranjosProducao = value;
    }

    /**
     * Gets the value of the cadeiasEstendida property.
     * 
     * @return
     *     possible object is
     *     {@link CadeiasEstendida }
     *     
     */
    public CadeiasEstendida getCadeiasEstendida() {
        return cadeiasEstendida;
    }

    /**
     * Sets the value of the cadeiasEstendida property.
     * 
     * @param value
     *     allowed object is
     *     {@link CadeiasEstendida }
     *     
     */
    public void setCadeiasEstendida(CadeiasEstendida value) {
        this.cadeiasEstendida = value;
    }

    /**
     * Gets the value of the capacidadesEstocagemMaxMin property.
     * 
     * @return
     *     possible object is
     *     {@link CapacidadesEstocagemMaxMin }
     *     
     */
    public CapacidadesEstocagemMaxMin getCapacidadesEstocagemMaxMin() {
        return capacidadesEstocagemMaxMin;
    }

    /**
     * Sets the value of the capacidadesEstocagemMaxMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapacidadesEstocagemMaxMin }
     *     
     */
    public void setCapacidadesEstocagemMaxMin(CapacidadesEstocagemMaxMin value) {
        this.capacidadesEstocagemMaxMin = value;
    }

    /**
     * Gets the value of the capacidadesBlendagem property.
     * 
     * @return
     *     possible object is
     *     {@link CapacidadesBlendagem }
     *     
     */
    public CapacidadesBlendagem getCapacidadesBlendagem() {
        return capacidadesBlendagem;
    }

    /**
     * Sets the value of the capacidadesBlendagem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapacidadesBlendagem }
     *     
     */
    public void setCapacidadesBlendagem(CapacidadesBlendagem value) {
        this.capacidadesBlendagem = value;
    }

    /**
     * Gets the value of the capacidadesMaxSobraLotes property.
     * 
     * @return
     *     possible object is
     *     {@link CapacidadesMaxSobraLotes }
     *     
     */
    public CapacidadesMaxSobraLotes getCapacidadesMaxSobraLotes() {
        return capacidadesMaxSobraLotes;
    }

    /**
     * Sets the value of the capacidadesMaxSobraLotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapacidadesMaxSobraLotes }
     *     
     */
    public void setCapacidadesMaxSobraLotes(CapacidadesMaxSobraLotes value) {
        this.capacidadesMaxSobraLotes = value;
    }

    /**
     * Gets the value of the capacidadesProducaoDisponibilizacaoElo property.
     * 
     * @return
     *     possible object is
     *     {@link CapacidadesProducaoDisponibilizacaoElo }
     *     
     */
    public CapacidadesProducaoDisponibilizacaoElo getCapacidadesProducaoDisponibilizacaoElo() {
        return capacidadesProducaoDisponibilizacaoElo;
    }

    /**
     * Sets the value of the capacidadesProducaoDisponibilizacaoElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapacidadesProducaoDisponibilizacaoElo }
     *     
     */
    public void setCapacidadesProducaoDisponibilizacaoElo(CapacidadesProducaoDisponibilizacaoElo value) {
        this.capacidadesProducaoDisponibilizacaoElo = value;
    }

    /**
     * Gets the value of the capacidadesProducaoDisponibilizacaoProdutoElo property.
     * 
     * @return
     *     possible object is
     *     {@link CapacidadesProducaoDisponibilizacaoProdutoElo }
     *     
     */
    public CapacidadesProducaoDisponibilizacaoProdutoElo getCapacidadesProducaoDisponibilizacaoProdutoElo() {
        return capacidadesProducaoDisponibilizacaoProdutoElo;
    }

    /**
     * Sets the value of the capacidadesProducaoDisponibilizacaoProdutoElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapacidadesProducaoDisponibilizacaoProdutoElo }
     *     
     */
    public void setCapacidadesProducaoDisponibilizacaoProdutoElo(CapacidadesProducaoDisponibilizacaoProdutoElo value) {
        this.capacidadesProducaoDisponibilizacaoProdutoElo = value;
    }

    /**
     * Gets the value of the capacidadesProducaoDisponibilizacaoProdutoHoraria property.
     * 
     * @return
     *     possible object is
     *     {@link CapacidadesProducaoDisponibilizacaoProdutoHoraria }
     *     
     */
    public CapacidadesProducaoDisponibilizacaoProdutoHoraria getCapacidadesProducaoDisponibilizacaoProdutoHoraria() {
        return capacidadesProducaoDisponibilizacaoProdutoHoraria;
    }

    /**
     * Sets the value of the capacidadesProducaoDisponibilizacaoProdutoHoraria property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapacidadesProducaoDisponibilizacaoProdutoHoraria }
     *     
     */
    public void setCapacidadesProducaoDisponibilizacaoProdutoHoraria(CapacidadesProducaoDisponibilizacaoProdutoHoraria value) {
        this.capacidadesProducaoDisponibilizacaoProdutoHoraria = value;
    }

    /**
     * Gets the value of the categoriasVendaAPS property.
     * 
     * @return
     *     possible object is
     *     {@link CategoriasVendaAPS }
     *     
     */
    public CategoriasVendaAPS getCategoriasVendaAPS() {
        return categoriasVendaAPS;
    }

    /**
     * Sets the value of the categoriasVendaAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoriasVendaAPS }
     *     
     */
    public void setCategoriasVendaAPS(CategoriasVendaAPS value) {
        this.categoriasVendaAPS = value;
    }

    /**
     * Gets the value of the classificacaoCompany property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificacaoCompany }
     *     
     */
    public ClassificacaoCompany getClassificacaoCompany() {
        return classificacaoCompany;
    }

    /**
     * Sets the value of the classificacaoCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificacaoCompany }
     *     
     */
    public void setClassificacaoCompany(ClassificacaoCompany value) {
        this.classificacaoCompany = value;
    }

    /**
     * Gets the value of the clientesAPS property.
     * 
     * @return
     *     possible object is
     *     {@link ClientesAPS }
     *     
     */
    public ClientesAPS getClientesAPS() {
        return clientesAPS;
    }

    /**
     * Sets the value of the clientesAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientesAPS }
     *     
     */
    public void setClientesAPS(ClientesAPS value) {
        this.clientesAPS = value;
    }

    /**
     * Gets the value of the complexosProdutivosAPS property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexosProdutivosAPS }
     *     
     */
    public ComplexosProdutivosAPS getComplexosProdutivosAPS() {
        return complexosProdutivosAPS;
    }

    /**
     * Sets the value of the complexosProdutivosAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexosProdutivosAPS }
     *     
     */
    public void setComplexosProdutivosAPS(ComplexosProdutivosAPS value) {
        this.complexosProdutivosAPS = value;
    }

    /**
     * Gets the value of the contratosTerceirosElo property.
     * 
     * @return
     *     possible object is
     *     {@link ContratosTerceirosElo }
     *     
     */
    public ContratosTerceirosElo getContratosTerceirosElo() {
        return contratosTerceirosElo;
    }

    /**
     * Sets the value of the contratosTerceirosElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContratosTerceirosElo }
     *     
     */
    public void setContratosTerceirosElo(ContratosTerceirosElo value) {
        this.contratosTerceirosElo = value;
    }

    /**
     * Gets the value of the contratosTerceirosEmpresaTransporte property.
     * 
     * @return
     *     possible object is
     *     {@link ContratosTerceirosEmpresaTransporte }
     *     
     */
    public ContratosTerceirosEmpresaTransporte getContratosTerceirosEmpresaTransporte() {
        return contratosTerceirosEmpresaTransporte;
    }

    /**
     * Sets the value of the contratosTerceirosEmpresaTransporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContratosTerceirosEmpresaTransporte }
     *     
     */
    public void setContratosTerceirosEmpresaTransporte(ContratosTerceirosEmpresaTransporte value) {
        this.contratosTerceirosEmpresaTransporte = value;
    }

    /**
     * Gets the value of the custosMina property.
     * 
     * @return
     *     possible object is
     *     {@link CustosMina }
     *     
     */
    public CustosMina getCustosMina() {
        return custosMina;
    }

    /**
     * Sets the value of the custosMina property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosMina }
     *     
     */
    public void setCustosMina(CustosMina value) {
        this.custosMina = value;
    }

    /**
     * Gets the value of the custosPatio property.
     * 
     * @return
     *     possible object is
     *     {@link CustosPatio }
     *     
     */
    public CustosPatio getCustosPatio() {
        return custosPatio;
    }

    /**
     * Sets the value of the custosPatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosPatio }
     *     
     */
    public void setCustosPatio(CustosPatio value) {
        this.custosPatio = value;
    }

    /**
     * Gets the value of the custosPorto property.
     * 
     * @return
     *     possible object is
     *     {@link CustosPorto }
     *     
     */
    public CustosPorto getCustosPorto() {
        return custosPorto;
    }

    /**
     * Sets the value of the custosPorto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosPorto }
     *     
     */
    public void setCustosPorto(CustosPorto value) {
        this.custosPorto = value;
    }

    /**
     * Gets the value of the custosSite property.
     * 
     * @return
     *     possible object is
     *     {@link CustosSite }
     *     
     */
    public CustosSite getCustosSite() {
        return custosSite;
    }

    /**
     * Sets the value of the custosSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosSite }
     *     
     */
    public void setCustosSite(CustosSite value) {
        this.custosSite = value;
    }

    /**
     * Gets the value of the custosUsinaBeneficiamento property.
     * 
     * @return
     *     possible object is
     *     {@link CustosUsinaBeneficiamento }
     *     
     */
    public CustosUsinaBeneficiamento getCustosUsinaBeneficiamento() {
        return custosUsinaBeneficiamento;
    }

    /**
     * Sets the value of the custosUsinaBeneficiamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosUsinaBeneficiamento }
     *     
     */
    public void setCustosUsinaBeneficiamento(CustosUsinaBeneficiamento value) {
        this.custosUsinaBeneficiamento = value;
    }

    /**
     * Gets the value of the custosUsinaBriquete property.
     * 
     * @return
     *     possible object is
     *     {@link CustosUsinaBriquete }
     *     
     */
    public CustosUsinaBriquete getCustosUsinaBriquete() {
        return custosUsinaBriquete;
    }

    /**
     * Sets the value of the custosUsinaBriquete property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosUsinaBriquete }
     *     
     */
    public void setCustosUsinaBriquete(CustosUsinaBriquete value) {
        this.custosUsinaBriquete = value;
    }

    /**
     * Gets the value of the custosUsinaPelotizacao property.
     * 
     * @return
     *     possible object is
     *     {@link CustosUsinaPelotizacao }
     *     
     */
    public CustosUsinaPelotizacao getCustosUsinaPelotizacao() {
        return custosUsinaPelotizacao;
    }

    /**
     * Sets the value of the custosUsinaPelotizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosUsinaPelotizacao }
     *     
     */
    public void setCustosUsinaPelotizacao(CustosUsinaPelotizacao value) {
        this.custosUsinaPelotizacao = value;
    }

    /**
     * Gets the value of the custosUsinaTransformacao property.
     * 
     * @return
     *     possible object is
     *     {@link CustosUsinaTransformacao }
     *     
     */
    public CustosUsinaTransformacao getCustosUsinaTransformacao() {
        return custosUsinaTransformacao;
    }

    /**
     * Sets the value of the custosUsinaTransformacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosUsinaTransformacao }
     *     
     */
    public void setCustosUsinaTransformacao(CustosUsinaTransformacao value) {
        this.custosUsinaTransformacao = value;
    }

    /**
     * Gets the value of the custosUtilizacaoEstoqueInicialPorSite property.
     * 
     * @return
     *     possible object is
     *     {@link CustosUtilizacaoEstoqueInicialPorSite }
     *     
     */
    public CustosUtilizacaoEstoqueInicialPorSite getCustosUtilizacaoEstoqueInicialPorSite() {
        return custosUtilizacaoEstoqueInicialPorSite;
    }

    /**
     * Sets the value of the custosUtilizacaoEstoqueInicialPorSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosUtilizacaoEstoqueInicialPorSite }
     *     
     */
    public void setCustosUtilizacaoEstoqueInicialPorSite(CustosUtilizacaoEstoqueInicialPorSite value) {
        this.custosUtilizacaoEstoqueInicialPorSite = value;
    }

    /**
     * Gets the value of the custosBlendagemPorto property.
     * 
     * @return
     *     possible object is
     *     {@link CustosBlendagemPorto }
     *     
     */
    public CustosBlendagemPorto getCustosBlendagemPorto() {
        return custosBlendagemPorto;
    }

    /**
     * Sets the value of the custosBlendagemPorto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosBlendagemPorto }
     *     
     */
    public void setCustosBlendagemPorto(CustosBlendagemPorto value) {
        this.custosBlendagemPorto = value;
    }

    /**
     * Gets the value of the custosEloCategoriaProduto property.
     * 
     * @return
     *     possible object is
     *     {@link CustosEloCategoriaProduto }
     *     
     */
    public CustosEloCategoriaProduto getCustosEloCategoriaProduto() {
        return custosEloCategoriaProduto;
    }

    /**
     * Sets the value of the custosEloCategoriaProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosEloCategoriaProduto }
     *     
     */
    public void setCustosEloCategoriaProduto(CustosEloCategoriaProduto value) {
        this.custosEloCategoriaProduto = value;
    }

    /**
     * Gets the value of the custosFerrovia property.
     * 
     * @return
     *     possible object is
     *     {@link CustosFerrovia }
     *     
     */
    public CustosFerrovia getCustosFerrovia() {
        return custosFerrovia;
    }

    /**
     * Sets the value of the custosFerrovia property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosFerrovia }
     *     
     */
    public void setCustosFerrovia(CustosFerrovia value) {
        this.custosFerrovia = value;
    }

    /**
     * Gets the value of the custosTrechoCategoriaProduto property.
     * 
     * @return
     *     possible object is
     *     {@link CustosTrechoCategoriaProduto }
     *     
     */
    public CustosTrechoCategoriaProduto getCustosTrechoCategoriaProduto() {
        return custosTrechoCategoriaProduto;
    }

    /**
     * Sets the value of the custosTrechoCategoriaProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustosTrechoCategoriaProduto }
     *     
     */
    public void setCustosTrechoCategoriaProduto(CustosTrechoCategoriaProduto value) {
        this.custosTrechoCategoriaProduto = value;
    }

    /**
     * Gets the value of the descontos property.
     * 
     * @return
     *     possible object is
     *     {@link Descontos }
     *     
     */
    public Descontos getDescontos() {
        return descontos;
    }

    /**
     * Sets the value of the descontos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Descontos }
     *     
     */
    public void setDescontos(Descontos value) {
        this.descontos = value;
    }

    /**
     * Gets the value of the desembaracos property.
     * 
     * @return
     *     possible object is
     *     {@link Desembaracos }
     *     
     */
    public Desembaracos getDesembaracos() {
        return desembaracos;
    }

    /**
     * Sets the value of the desembaracos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Desembaracos }
     *     
     */
    public void setDesembaracos(Desembaracos value) {
        this.desembaracos = value;
    }

    /**
     * Gets the value of the disponibilidadesAPS property.
     * 
     * @return
     *     possible object is
     *     {@link DisponibilidadesAPS }
     *     
     */
    public DisponibilidadesAPS getDisponibilidadesAPS() {
        return disponibilidadesAPS;
    }

    /**
     * Sets the value of the disponibilidadesAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisponibilidadesAPS }
     *     
     */
    public void setDisponibilidadesAPS(DisponibilidadesAPS value) {
        this.disponibilidadesAPS = value;
    }

    /**
     * Gets the value of the disponibilidadesCompatibilidadeDetalheAPS property.
     * 
     * @return
     *     possible object is
     *     {@link DisponibilidadesCompatibilidadeDetalheAPS }
     *     
     */
    public DisponibilidadesCompatibilidadeDetalheAPS getDisponibilidadesCompatibilidadeDetalheAPS() {
        return disponibilidadesCompatibilidadeDetalheAPS;
    }

    /**
     * Sets the value of the disponibilidadesCompatibilidadeDetalheAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisponibilidadesCompatibilidadeDetalheAPS }
     *     
     */
    public void setDisponibilidadesCompatibilidadeDetalheAPS(DisponibilidadesCompatibilidadeDetalheAPS value) {
        this.disponibilidadesCompatibilidadeDetalheAPS = value;
    }

    /**
     * Gets the value of the disponibilidadesDetalheAPS property.
     * 
     * @return
     *     possible object is
     *     {@link DisponibilidadesDetalheAPS }
     *     
     */
    public DisponibilidadesDetalheAPS getDisponibilidadesDetalheAPS() {
        return disponibilidadesDetalheAPS;
    }

    /**
     * Sets the value of the disponibilidadesDetalheAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisponibilidadesDetalheAPS }
     *     
     */
    public void setDisponibilidadesDetalheAPS(DisponibilidadesDetalheAPS value) {
        this.disponibilidadesDetalheAPS = value;
    }

    /**
     * Gets the value of the disponibilidadesEstoqueInicial property.
     * 
     * @return
     *     possible object is
     *     {@link DisponibilidadesEstoqueInicial }
     *     
     */
    public DisponibilidadesEstoqueInicial getDisponibilidadesEstoqueInicial() {
        return disponibilidadesEstoqueInicial;
    }

    /**
     * Sets the value of the disponibilidadesEstoqueInicial property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisponibilidadesEstoqueInicial }
     *     
     */
    public void setDisponibilidadesEstoqueInicial(DisponibilidadesEstoqueInicial value) {
        this.disponibilidadesEstoqueInicial = value;
    }

    /**
     * Gets the value of the distribuicoesMensaisCadeia property.
     * 
     * @return
     *     possible object is
     *     {@link DistribuicoesMensaisCadeia }
     *     
     */
    public DistribuicoesMensaisCadeia getDistribuicoesMensaisCadeia() {
        return distribuicoesMensaisCadeia;
    }

    /**
     * Sets the value of the distribuicoesMensaisCadeia property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistribuicoesMensaisCadeia }
     *     
     */
    public void setDistribuicoesMensaisCadeia(DistribuicoesMensaisCadeia value) {
        this.distribuicoesMensaisCadeia = value;
    }

    /**
     * Gets the value of the escritoriosAPS property.
     * 
     * @return
     *     possible object is
     *     {@link EscritoriosAPS }
     *     
     */
    public EscritoriosAPS getEscritoriosAPS() {
        return escritoriosAPS;
    }

    /**
     * Sets the value of the escritoriosAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link EscritoriosAPS }
     *     
     */
    public void setEscritoriosAPS(EscritoriosAPS value) {
        this.escritoriosAPS = value;
    }

    /**
     * Gets the value of the estoquesEstrategicos property.
     * 
     * @return
     *     possible object is
     *     {@link EstoquesEstrategicos }
     *     
     */
    public EstoquesEstrategicos getEstoquesEstrategicos() {
        return estoquesEstrategicos;
    }

    /**
     * Sets the value of the estoquesEstrategicos property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstoquesEstrategicos }
     *     
     */
    public void setEstoquesEstrategicos(EstoquesEstrategicos value) {
        this.estoquesEstrategicos = value;
    }

    /**
     * Gets the value of the estoquesIniciais property.
     * 
     * @return
     *     possible object is
     *     {@link EstoquesIniciais }
     *     
     */
    public EstoquesIniciais getEstoquesIniciais() {
        return estoquesIniciais;
    }

    /**
     * Sets the value of the estoquesIniciais property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstoquesIniciais }
     *     
     */
    public void setEstoquesIniciais(EstoquesIniciais value) {
        this.estoquesIniciais = value;
    }

    /**
     * Gets the value of the expedicoesMinimas property.
     * 
     * @return
     *     possible object is
     *     {@link ExpedicoesMinimas }
     *     
     */
    public ExpedicoesMinimas getExpedicoesMinimas() {
        return expedicoesMinimas;
    }

    /**
     * Sets the value of the expedicoesMinimas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpedicoesMinimas }
     *     
     */
    public void setExpedicoesMinimas(ExpedicoesMinimas value) {
        this.expedicoesMinimas = value;
    }

    /**
     * Gets the value of the faixaCustoFreteAdicionalList property.
     * 
     * @return
     *     possible object is
     *     {@link FaixaCustoFreteAdicionalList }
     *     
     */
    public FaixaCustoFreteAdicionalList getFaixaCustoFreteAdicionalList() {
        return faixaCustoFreteAdicionalList;
    }

    /**
     * Sets the value of the faixaCustoFreteAdicionalList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaixaCustoFreteAdicionalList }
     *     
     */
    public void setFaixaCustoFreteAdicionalList(FaixaCustoFreteAdicionalList value) {
        this.faixaCustoFreteAdicionalList = value;
    }

    /**
     * Gets the value of the faixaCustoFreteAdicionalTrechos property.
     * 
     * @return
     *     possible object is
     *     {@link FaixaCustoFreteAdicionalTrechos }
     *     
     */
    public FaixaCustoFreteAdicionalTrechos getFaixaCustoFreteAdicionalTrechos() {
        return faixaCustoFreteAdicionalTrechos;
    }

    /**
     * Sets the value of the faixaCustoFreteAdicionalTrechos property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaixaCustoFreteAdicionalTrechos }
     *     
     */
    public void setFaixaCustoFreteAdicionalTrechos(FaixaCustoFreteAdicionalTrechos value) {
        this.faixaCustoFreteAdicionalTrechos = value;
    }

    /**
     * Gets the value of the faixasEqualizacaoQualidade property.
     * 
     * @return
     *     possible object is
     *     {@link FaixasEqualizacaoQualidade }
     *     
     */
    public FaixasEqualizacaoQualidade getFaixasEqualizacaoQualidade() {
        return faixasEqualizacaoQualidade;
    }

    /**
     * Sets the value of the faixasEqualizacaoQualidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaixasEqualizacaoQualidade }
     *     
     */
    public void setFaixasEqualizacaoQualidade(FaixasEqualizacaoQualidade value) {
        this.faixasEqualizacaoQualidade = value;
    }

    /**
     * Gets the value of the faixasCustoFreteAdicionalList property.
     * 
     * @return
     *     possible object is
     *     {@link FaixasCustoFreteAdicionalList }
     *     
     */
    public FaixasCustoFreteAdicionalList getFaixasCustoFreteAdicionalList() {
        return faixasCustoFreteAdicionalList;
    }

    /**
     * Sets the value of the faixasCustoFreteAdicionalList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaixasCustoFreteAdicionalList }
     *     
     */
    public void setFaixasCustoFreteAdicionalList(FaixasCustoFreteAdicionalList value) {
        this.faixasCustoFreteAdicionalList = value;
    }

    /**
     * Gets the value of the finosDePelota property.
     * 
     * @return
     *     possible object is
     *     {@link FinosDePelota }
     *     
     */
    public FinosDePelota getFinosDePelota() {
        return finosDePelota;
    }

    /**
     * Sets the value of the finosDePelota property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinosDePelota }
     *     
     */
    public void setFinosDePelota(FinosDePelota value) {
        this.finosDePelota = value;
    }

    /**
     * Gets the value of the fornecedoresAPS property.
     * 
     * @return
     *     possible object is
     *     {@link FornecedoresAPS }
     *     
     */
    public FornecedoresAPS getFornecedoresAPS() {
        return fornecedoresAPS;
    }

    /**
     * Sets the value of the fornecedoresAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link FornecedoresAPS }
     *     
     */
    public void setFornecedoresAPS(FornecedoresAPS value) {
        this.fornecedoresAPS = value;
    }

    /**
     * Gets the value of the grupoClienteAPS property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoClienteAPS }
     *     
     */
    public GrupoClienteAPS getGrupoClienteAPS() {
        return grupoClienteAPS;
    }

    /**
     * Sets the value of the grupoClienteAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoClienteAPS }
     *     
     */
    public void setGrupoClienteAPS(GrupoClienteAPS value) {
        this.grupoClienteAPS = value;
    }

    /**
     * Gets the value of the grupoPorto property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoPorto }
     *     
     */
    public GrupoPorto getGrupoPorto() {
        return grupoPorto;
    }

    /**
     * Sets the value of the grupoPorto property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoPorto }
     *     
     */
    public void setGrupoPorto(GrupoPorto value) {
        this.grupoPorto = value;
    }

    /**
     * Gets the value of the gruposProdutosExclusivos property.
     * 
     * @return
     *     possible object is
     *     {@link GruposProdutosExclusivos }
     *     
     */
    public GruposProdutosExclusivos getGruposProdutosExclusivos() {
        return gruposProdutosExclusivos;
    }

    /**
     * Sets the value of the gruposProdutosExclusivos property.
     * 
     * @param value
     *     allowed object is
     *     {@link GruposProdutosExclusivos }
     *     
     */
    public void setGruposProdutosExclusivos(GruposProdutosExclusivos value) {
        this.gruposProdutosExclusivos = value;
    }

    /**
     * Gets the value of the historicoAssociacoesElo property.
     * 
     * @return
     *     possible object is
     *     {@link HistoricoAssociacoesElo }
     *     
     */
    public HistoricoAssociacoesElo getHistoricoAssociacoesElo() {
        return historicoAssociacoesElo;
    }

    /**
     * Sets the value of the historicoAssociacoesElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoricoAssociacoesElo }
     *     
     */
    public void setHistoricoAssociacoesElo(HistoricoAssociacoesElo value) {
        this.historicoAssociacoesElo = value;
    }

    /**
     * Gets the value of the indicesReferencia property.
     * 
     * @return
     *     possible object is
     *     {@link IndicesReferencia }
     *     
     */
    public IndicesReferencia getIndicesReferencia() {
        return indicesReferencia;
    }

    /**
     * Sets the value of the indicesReferencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicesReferencia }
     *     
     */
    public void setIndicesReferencia(IndicesReferencia value) {
        this.indicesReferencia = value;
    }

    /**
     * Gets the value of the instalacoesUsinaBeneficiamento property.
     * 
     * @return
     *     possible object is
     *     {@link InstalacoesUsinaBeneficiamento }
     *     
     */
    public InstalacoesUsinaBeneficiamento getInstalacoesUsinaBeneficiamento() {
        return instalacoesUsinaBeneficiamento;
    }

    /**
     * Sets the value of the instalacoesUsinaBeneficiamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstalacoesUsinaBeneficiamento }
     *     
     */
    public void setInstalacoesUsinaBeneficiamento(InstalacoesUsinaBeneficiamento value) {
        this.instalacoesUsinaBeneficiamento = value;
    }

    /**
     * Gets the value of the layDayTamanhosEmbarque property.
     * 
     * @return
     *     possible object is
     *     {@link LayDayTamanhosEmbarque }
     *     
     */
    public LayDayTamanhosEmbarque getLayDayTamanhosEmbarque() {
        return layDayTamanhosEmbarque;
    }

    /**
     * Sets the value of the layDayTamanhosEmbarque property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayDayTamanhosEmbarque }
     *     
     */
    public void setLayDayTamanhosEmbarque(LayDayTamanhosEmbarque value) {
        this.layDayTamanhosEmbarque = value;
    }

    /**
     * Gets the value of the limitesProducaoDisponibilizacaoElo property.
     * 
     * @return
     *     possible object is
     *     {@link LimitesProducaoDisponibilizacaoElo }
     *     
     */
    public LimitesProducaoDisponibilizacaoElo getLimitesProducaoDisponibilizacaoElo() {
        return limitesProducaoDisponibilizacaoElo;
    }

    /**
     * Sets the value of the limitesProducaoDisponibilizacaoElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitesProducaoDisponibilizacaoElo }
     *     
     */
    public void setLimitesProducaoDisponibilizacaoElo(LimitesProducaoDisponibilizacaoElo value) {
        this.limitesProducaoDisponibilizacaoElo = value;
    }

    /**
     * Gets the value of the limitesProducaoDisponibilizacaoProdutoElo property.
     * 
     * @return
     *     possible object is
     *     {@link LimitesProducaoDisponibilizacaoProdutoElo }
     *     
     */
    public LimitesProducaoDisponibilizacaoProdutoElo getLimitesProducaoDisponibilizacaoProdutoElo() {
        return limitesProducaoDisponibilizacaoProdutoElo;
    }

    /**
     * Sets the value of the limitesProducaoDisponibilizacaoProdutoElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitesProducaoDisponibilizacaoProdutoElo }
     *     
     */
    public void setLimitesProducaoDisponibilizacaoProdutoElo(LimitesProducaoDisponibilizacaoProdutoElo value) {
        this.limitesProducaoDisponibilizacaoProdutoElo = value;
    }

    /**
     * Gets the value of the manutencoesElo property.
     * 
     * @return
     *     possible object is
     *     {@link ManutencoesElo }
     *     
     */
    public ManutencoesElo getManutencoesElo() {
        return manutencoesElo;
    }

    /**
     * Sets the value of the manutencoesElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManutencoesElo }
     *     
     */
    public void setManutencoesElo(ManutencoesElo value) {
        this.manutencoesElo = value;
    }

    /**
     * Gets the value of the minasAPS property.
     * 
     * @return
     *     possible object is
     *     {@link MinasAPS }
     *     
     */
    public MinasAPS getMinasAPS() {
        return minasAPS;
    }

    /**
     * Sets the value of the minasAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinasAPS }
     *     
     */
    public void setMinasAPS(MinasAPS value) {
        this.minasAPS = value;
    }

    /**
     * Gets the value of the multasBonificacaoContratoTransporte property.
     * 
     * @return
     *     possible object is
     *     {@link MultasBonificacaoContratoTransporte }
     *     
     */
    public MultasBonificacaoContratoTransporte getMultasBonificacaoContratoTransporte() {
        return multasBonificacaoContratoTransporte;
    }

    /**
     * Sets the value of the multasBonificacaoContratoTransporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultasBonificacaoContratoTransporte }
     *     
     */
    public void setMultasBonificacaoContratoTransporte(MultasBonificacaoContratoTransporte value) {
        this.multasBonificacaoContratoTransporte = value;
    }

    /**
     * Gets the value of the parametrosCorporativos property.
     * 
     * @return
     *     possible object is
     *     {@link ParametrosCorporativos }
     *     
     */
    public ParametrosCorporativos getParametrosCorporativos() {
        return parametrosCorporativos;
    }

    /**
     * Sets the value of the parametrosCorporativos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametrosCorporativos }
     *     
     */
    public void setParametrosCorporativos(ParametrosCorporativos value) {
        this.parametrosCorporativos = value;
    }

    /**
     * Gets the value of the parametrosEqualizacaoQualidade property.
     * 
     * @return
     *     possible object is
     *     {@link ParametrosEqualizacaoQualidade }
     *     
     */
    public ParametrosEqualizacaoQualidade getParametrosEqualizacaoQualidade() {
        return parametrosEqualizacaoQualidade;
    }

    /**
     * Sets the value of the parametrosEqualizacaoQualidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametrosEqualizacaoQualidade }
     *     
     */
    public void setParametrosEqualizacaoQualidade(ParametrosEqualizacaoQualidade value) {
        this.parametrosEqualizacaoQualidade = value;
    }

    /**
     * Gets the value of the patiosAPS property.
     * 
     * @return
     *     possible object is
     *     {@link PatiosAPS }
     *     
     */
    public PatiosAPS getPatiosAPS() {
        return patiosAPS;
    }

    /**
     * Sets the value of the patiosAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatiosAPS }
     *     
     */
    public void setPatiosAPS(PatiosAPS value) {
        this.patiosAPS = value;
    }

    /**
     * Gets the value of the peneiramentosAPS property.
     * 
     * @return
     *     possible object is
     *     {@link PeneiramentosAPS }
     *     
     */
    public PeneiramentosAPS getPeneiramentosAPS() {
        return peneiramentosAPS;
    }

    /**
     * Sets the value of the peneiramentosAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeneiramentosAPS }
     *     
     */
    public void setPeneiramentosAPS(PeneiramentosAPS value) {
        this.peneiramentosAPS = value;
    }

    /**
     * Gets the value of the percentuaisAtendimentoTrimestreAPS property.
     * 
     * @return
     *     possible object is
     *     {@link PercentuaisAtendimentoTrimestreAPS }
     *     
     */
    public PercentuaisAtendimentoTrimestreAPS getPercentuaisAtendimentoTrimestreAPS() {
        return percentuaisAtendimentoTrimestreAPS;
    }

    /**
     * Sets the value of the percentuaisAtendimentoTrimestreAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentuaisAtendimentoTrimestreAPS }
     *     
     */
    public void setPercentuaisAtendimentoTrimestreAPS(PercentuaisAtendimentoTrimestreAPS value) {
        this.percentuaisAtendimentoTrimestreAPS = value;
    }

    /**
     * Gets the value of the pilhasPadrao property.
     * 
     * @return
     *     possible object is
     *     {@link PilhasPadrao }
     *     
     */
    public PilhasPadrao getPilhasPadrao() {
        return pilhasPadrao;
    }

    /**
     * Sets the value of the pilhasPadrao property.
     * 
     * @param value
     *     allowed object is
     *     {@link PilhasPadrao }
     *     
     */
    public void setPilhasPadrao(PilhasPadrao value) {
        this.pilhasPadrao = value;
    }

    /**
     * Gets the value of the planejamentosEmbarques property.
     * 
     * @return
     *     possible object is
     *     {@link PlanejamentosEmbarques }
     *     
     */
    public PlanejamentosEmbarques getPlanejamentosEmbarques() {
        return planejamentosEmbarques;
    }

    /**
     * Sets the value of the planejamentosEmbarques property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanejamentosEmbarques }
     *     
     */
    public void setPlanejamentosEmbarques(PlanejamentosEmbarques value) {
        this.planejamentosEmbarques = value;
    }

    /**
     * Gets the value of the planosContratacaoAPS property.
     * 
     * @return
     *     possible object is
     *     {@link PlanosContratacaoAPS }
     *     
     */
    public PlanosContratacaoAPS getPlanosContratacaoAPS() {
        return planosContratacaoAPS;
    }

    /**
     * Sets the value of the planosContratacaoAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanosContratacaoAPS }
     *     
     */
    public void setPlanosContratacaoAPS(PlanosContratacaoAPS value) {
        this.planosContratacaoAPS = value;
    }

    /**
     * Gets the value of the planosContratacaoDetalheAPS property.
     * 
     * @return
     *     possible object is
     *     {@link PlanosContratacaoDetalheAPS }
     *     
     */
    public PlanosContratacaoDetalheAPS getPlanosContratacaoDetalheAPS() {
        return planosContratacaoDetalheAPS;
    }

    /**
     * Sets the value of the planosContratacaoDetalheAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanosContratacaoDetalheAPS }
     *     
     */
    public void setPlanosContratacaoDetalheAPS(PlanosContratacaoDetalheAPS value) {
        this.planosContratacaoDetalheAPS = value;
    }

    /**
     * Gets the value of the pontosCargaDescargaAPS property.
     * 
     * @return
     *     possible object is
     *     {@link PontosCargaDescargaAPS }
     *     
     */
    public PontosCargaDescargaAPS getPontosCargaDescargaAPS() {
        return pontosCargaDescargaAPS;
    }

    /**
     * Sets the value of the pontosCargaDescargaAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PontosCargaDescargaAPS }
     *     
     */
    public void setPontosCargaDescargaAPS(PontosCargaDescargaAPS value) {
        this.pontosCargaDescargaAPS = value;
    }

    /**
     * Gets the value of the portosAPS property.
     * 
     * @return
     *     possible object is
     *     {@link PortosAPS }
     *     
     */
    public PortosAPS getPortosAPS() {
        return portosAPS;
    }

    /**
     * Sets the value of the portosAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortosAPS }
     *     
     */
    public void setPortosAPS(PortosAPS value) {
        this.portosAPS = value;
    }

    /**
     * Gets the value of the previsoesCargaCaminhaoAsia property.
     * 
     * @return
     *     possible object is
     *     {@link PrevisoesCargaCaminhaoAsia }
     *     
     */
    public PrevisoesCargaCaminhaoAsia getPrevisoesCargaCaminhaoAsia() {
        return previsoesCargaCaminhaoAsia;
    }

    /**
     * Sets the value of the previsoesCargaCaminhaoAsia property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrevisoesCargaCaminhaoAsia }
     *     
     */
    public void setPrevisoesCargaCaminhaoAsia(PrevisoesCargaCaminhaoAsia value) {
        this.previsoesCargaCaminhaoAsia = value;
    }

    /**
     * Gets the value of the previsoesCargaNavio property.
     * 
     * @return
     *     possible object is
     *     {@link PrevisoesCargaNavio }
     *     
     */
    public PrevisoesCargaNavio getPrevisoesCargaNavio() {
        return previsoesCargaNavio;
    }

    /**
     * Sets the value of the previsoesCargaNavio property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrevisoesCargaNavio }
     *     
     */
    public void setPrevisoesCargaNavio(PrevisoesCargaNavio value) {
        this.previsoesCargaNavio = value;
    }

    /**
     * Gets the value of the prioridadesPlanoAPS property.
     * 
     * @return
     *     possible object is
     *     {@link PrioridadesPlanoAPS }
     *     
     */
    public PrioridadesPlanoAPS getPrioridadesPlanoAPS() {
        return prioridadesPlanoAPS;
    }

    /**
     * Sets the value of the prioridadesPlanoAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrioridadesPlanoAPS }
     *     
     */
    public void setPrioridadesPlanoAPS(PrioridadesPlanoAPS value) {
        this.prioridadesPlanoAPS = value;
    }

    /**
     * Gets the value of the processosImportacaoAsia property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessosImportacaoAsia }
     *     
     */
    public ProcessosImportacaoAsia getProcessosImportacaoAsia() {
        return processosImportacaoAsia;
    }

    /**
     * Sets the value of the processosImportacaoAsia property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessosImportacaoAsia }
     *     
     */
    public void setProcessosImportacaoAsia(ProcessosImportacaoAsia value) {
        this.processosImportacaoAsia = value;
    }

    /**
     * Gets the value of the produtosArranjo property.
     * 
     * @return
     *     possible object is
     *     {@link ProdutosArranjo }
     *     
     */
    public ProdutosArranjo getProdutosArranjo() {
        return produtosArranjo;
    }

    /**
     * Sets the value of the produtosArranjo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProdutosArranjo }
     *     
     */
    public void setProdutosArranjo(ProdutosArranjo value) {
        this.produtosArranjo = value;
    }

    /**
     * Gets the value of the produtosExclusivosArranjo property.
     * 
     * @return
     *     possible object is
     *     {@link ProdutosExclusivosArranjo }
     *     
     */
    public ProdutosExclusivosArranjo getProdutosExclusivosArranjo() {
        return produtosExclusivosArranjo;
    }

    /**
     * Sets the value of the produtosExclusivosArranjo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProdutosExclusivosArranjo }
     *     
     */
    public void setProdutosExclusivosArranjo(ProdutosExclusivosArranjo value) {
        this.produtosExclusivosArranjo = value;
    }

    /**
     * Gets the value of the qualidadesProdutoElo property.
     * 
     * @return
     *     possible object is
     *     {@link QualidadesProdutoElo }
     *     
     */
    public QualidadesProdutoElo getQualidadesProdutoElo() {
        return qualidadesProdutoElo;
    }

    /**
     * Sets the value of the qualidadesProdutoElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualidadesProdutoElo }
     *     
     */
    public void setQualidadesProdutoElo(QualidadesProdutoElo value) {
        this.qualidadesProdutoElo = value;
    }

    /**
     * Gets the value of the receitasCusto property.
     * 
     * @return
     *     possible object is
     *     {@link ReceitasCusto }
     *     
     */
    public ReceitasCusto getReceitasCusto() {
        return receitasCusto;
    }

    /**
     * Sets the value of the receitasCusto property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceitasCusto }
     *     
     */
    public void setReceitasCusto(ReceitasCusto value) {
        this.receitasCusto = value;
    }

    /**
     * Gets the value of the recuperacoesMassaAsia property.
     * 
     * @return
     *     possible object is
     *     {@link RecuperacoesMassaAsia }
     *     
     */
    public RecuperacoesMassaAsia getRecuperacoesMassaAsia() {
        return recuperacoesMassaAsia;
    }

    /**
     * Sets the value of the recuperacoesMassaAsia property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecuperacoesMassaAsia }
     *     
     */
    public void setRecuperacoesMassaAsia(RecuperacoesMassaAsia value) {
        this.recuperacoesMassaAsia = value;
    }

    /**
     * Gets the value of the regioesAPS property.
     * 
     * @return
     *     possible object is
     *     {@link RegioesAPS }
     *     
     */
    public RegioesAPS getRegioesAPS() {
        return regioesAPS;
    }

    /**
     * Sets the value of the regioesAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegioesAPS }
     *     
     */
    public void setRegioesAPS(RegioesAPS value) {
        this.regioesAPS = value;
    }

    /**
     * Gets the value of the regrasTransformacaoUsina property.
     * 
     * @return
     *     possible object is
     *     {@link RegrasTransformacaoUsina }
     *     
     */
    public RegrasTransformacaoUsina getRegrasTransformacaoUsina() {
        return regrasTransformacaoUsina;
    }

    /**
     * Sets the value of the regrasTransformacaoUsina property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegrasTransformacaoUsina }
     *     
     */
    public void setRegrasTransformacaoUsina(RegrasTransformacaoUsina value) {
        this.regrasTransformacaoUsina = value;
    }

    /**
     * Gets the value of the regrasTransformacaoUsinaPelotizacao property.
     * 
     * @return
     *     possible object is
     *     {@link RegrasTransformacaoUsinaPelotizacao }
     *     
     */
    public RegrasTransformacaoUsinaPelotizacao getRegrasTransformacaoUsinaPelotizacao() {
        return regrasTransformacaoUsinaPelotizacao;
    }

    /**
     * Sets the value of the regrasTransformacaoUsinaPelotizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegrasTransformacaoUsinaPelotizacao }
     *     
     */
    public void setRegrasTransformacaoUsinaPelotizacao(RegrasTransformacaoUsinaPelotizacao value) {
        this.regrasTransformacaoUsinaPelotizacao = value;
    }

    /**
     * Gets the value of the sistemasProducaoAPS property.
     * 
     * @return
     *     possible object is
     *     {@link SistemasProducaoAPS }
     *     
     */
    public SistemasProducaoAPS getSistemasProducaoAPS() {
        return sistemasProducaoAPS;
    }

    /**
     * Sets the value of the sistemasProducaoAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link SistemasProducaoAPS }
     *     
     */
    public void setSistemasProducaoAPS(SistemasProducaoAPS value) {
        this.sistemasProducaoAPS = value;
    }

    /**
     * Gets the value of the sitesProdutivosAPS property.
     * 
     * @return
     *     possible object is
     *     {@link SitesProdutivosAPS }
     *     
     */
    public SitesProdutivosAPS getSitesProdutivosAPS() {
        return sitesProdutivosAPS;
    }

    /**
     * Sets the value of the sitesProdutivosAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link SitesProdutivosAPS }
     *     
     */
    public void setSitesProdutivosAPS(SitesProdutivosAPS value) {
        this.sitesProdutivosAPS = value;
    }

    /**
     * Gets the value of the splitsInstalacaoAPS property.
     * 
     * @return
     *     possible object is
     *     {@link SplitsInstalacaoAPS }
     *     
     */
    public SplitsInstalacaoAPS getSplitsInstalacaoAPS() {
        return splitsInstalacaoAPS;
    }

    /**
     * Sets the value of the splitsInstalacaoAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitsInstalacaoAPS }
     *     
     */
    public void setSplitsInstalacaoAPS(SplitsInstalacaoAPS value) {
        this.splitsInstalacaoAPS = value;
    }

    /**
     * Gets the value of the taxasDescargaExpedicaoElo property.
     * 
     * @return
     *     possible object is
     *     {@link TaxasDescargaExpedicaoElo }
     *     
     */
    public TaxasDescargaExpedicaoElo getTaxasDescargaExpedicaoElo() {
        return taxasDescargaExpedicaoElo;
    }

    /**
     * Sets the value of the taxasDescargaExpedicaoElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxasDescargaExpedicaoElo }
     *     
     */
    public void setTaxasDescargaExpedicaoElo(TaxasDescargaExpedicaoElo value) {
        this.taxasDescargaExpedicaoElo = value;
    }

    /**
     * Gets the value of the tiposNavios property.
     * 
     * @return
     *     possible object is
     *     {@link TiposNavios }
     *     
     */
    public TiposNavios getTiposNavios() {
        return tiposNavios;
    }

    /**
     * Sets the value of the tiposNavios property.
     * 
     * @param value
     *     allowed object is
     *     {@link TiposNavios }
     *     
     */
    public void setTiposNavios(TiposNavios value) {
        this.tiposNavios = value;
    }

    /**
     * Gets the value of the tiposPrecificacoesCliente property.
     * 
     * @return
     *     possible object is
     *     {@link TiposPrecificacoesCliente }
     *     
     */
    public TiposPrecificacoesCliente getTiposPrecificacoesCliente() {
        return tiposPrecificacoesCliente;
    }

    /**
     * Sets the value of the tiposPrecificacoesCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link TiposPrecificacoesCliente }
     *     
     */
    public void setTiposPrecificacoesCliente(TiposPrecificacoesCliente value) {
        this.tiposPrecificacoesCliente = value;
    }

    /**
     * Gets the value of the trechosContratoTerceiroTransporte property.
     * 
     * @return
     *     possible object is
     *     {@link TrechosContratoTerceiroTransporte }
     *     
     */
    public TrechosContratoTerceiroTransporte getTrechosContratoTerceiroTransporte() {
        return trechosContratoTerceiroTransporte;
    }

    /**
     * Sets the value of the trechosContratoTerceiroTransporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrechosContratoTerceiroTransporte }
     *     
     */
    public void setTrechosContratoTerceiroTransporte(TrechosContratoTerceiroTransporte value) {
        this.trechosContratoTerceiroTransporte = value;
    }

    /**
     * Gets the value of the usinasAsia property.
     * 
     * @return
     *     possible object is
     *     {@link UsinasAsia }
     *     
     */
    public UsinasAsia getUsinasAsia() {
        return usinasAsia;
    }

    /**
     * Sets the value of the usinasAsia property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsinasAsia }
     *     
     */
    public void setUsinasAsia(UsinasAsia value) {
        this.usinasAsia = value;
    }

    /**
     * Gets the value of the usinasBeneficiamentoAPS property.
     * 
     * @return
     *     possible object is
     *     {@link UsinasBeneficiamentoAPS }
     *     
     */
    public UsinasBeneficiamentoAPS getUsinasBeneficiamentoAPS() {
        return usinasBeneficiamentoAPS;
    }

    /**
     * Sets the value of the usinasBeneficiamentoAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsinasBeneficiamentoAPS }
     *     
     */
    public void setUsinasBeneficiamentoAPS(UsinasBeneficiamentoAPS value) {
        this.usinasBeneficiamentoAPS = value;
    }

    /**
     * Gets the value of the usinasBriqueteAPS property.
     * 
     * @return
     *     possible object is
     *     {@link UsinasBriqueteAPS }
     *     
     */
    public UsinasBriqueteAPS getUsinasBriqueteAPS() {
        return usinasBriqueteAPS;
    }

    /**
     * Sets the value of the usinasBriqueteAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsinasBriqueteAPS }
     *     
     */
    public void setUsinasBriqueteAPS(UsinasBriqueteAPS value) {
        this.usinasBriqueteAPS = value;
    }

    /**
     * Gets the value of the usinasPelotizacaoAPS property.
     * 
     * @return
     *     possible object is
     *     {@link UsinasPelotizacaoAPS }
     *     
     */
    public UsinasPelotizacaoAPS getUsinasPelotizacaoAPS() {
        return usinasPelotizacaoAPS;
    }

    /**
     * Sets the value of the usinasPelotizacaoAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsinasPelotizacaoAPS }
     *     
     */
    public void setUsinasPelotizacaoAPS(UsinasPelotizacaoAPS value) {
        this.usinasPelotizacaoAPS = value;
    }

    /**
     * Gets the value of the usinasTransformacaoAPS property.
     * 
     * @return
     *     possible object is
     *     {@link UsinasTransformacaoAPS }
     *     
     */
    public UsinasTransformacaoAPS getUsinasTransformacaoAPS() {
        return usinasTransformacaoAPS;
    }

    /**
     * Sets the value of the usinasTransformacaoAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsinasTransformacaoAPS }
     *     
     */
    public void setUsinasTransformacaoAPS(UsinasTransformacaoAPS value) {
        this.usinasTransformacaoAPS = value;
    }

    /**
     * Gets the value of the utilizacoesEstoqueInicial property.
     * 
     * @return
     *     possible object is
     *     {@link UtilizacoesEstoqueInicial }
     *     
     */
    public UtilizacoesEstoqueInicial getUtilizacoesEstoqueInicial() {
        return utilizacoesEstoqueInicial;
    }

    /**
     * Sets the value of the utilizacoesEstoqueInicial property.
     * 
     * @param value
     *     allowed object is
     *     {@link UtilizacoesEstoqueInicial }
     *     
     */
    public void setUtilizacoesEstoqueInicial(UtilizacoesEstoqueInicial value) {
        this.utilizacoesEstoqueInicial = value;
    }

    /**
     * Gets the value of the utilizacoesProgramadasInstalacao property.
     * 
     * @return
     *     possible object is
     *     {@link UtilizacoesProgramadasInstalacao }
     *     
     */
    public UtilizacoesProgramadasInstalacao getUtilizacoesProgramadasInstalacao() {
        return utilizacoesProgramadasInstalacao;
    }

    /**
     * Sets the value of the utilizacoesProgramadasInstalacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link UtilizacoesProgramadasInstalacao }
     *     
     */
    public void setUtilizacoesProgramadasInstalacao(UtilizacoesProgramadasInstalacao value) {
        this.utilizacoesProgramadasInstalacao = value;
    }

    /**
     * Gets the value of the validadesEstoque property.
     * 
     * @return
     *     possible object is
     *     {@link ValidadesEstoque }
     *     
     */
    public ValidadesEstoque getValidadesEstoque() {
        return validadesEstoque;
    }

    /**
     * Sets the value of the validadesEstoque property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidadesEstoque }
     *     
     */
    public void setValidadesEstoque(ValidadesEstoque value) {
        this.validadesEstoque = value;
    }

}
