//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.22 at 08:27:36 PM UTC
//


package inteli.sudeste;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}capacidadeMax" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element ref="{}codigoCategoriaProduto"/&gt;
 *           &lt;element ref="{}codigoGrupoProduto"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element ref="{}capacidadeMin"/&gt;
 *           &lt;element ref="{}capacidadeMaxContract"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}codigoProduto" minOccurs="0"/&gt;
 *         &lt;element ref="{}data"/&gt;
 *         &lt;element ref="{}dataInicioVigenciaGrupoProduto" minOccurs="0"/&gt;
 *         &lt;element ref="{}habilitarRestricao"/&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}idElo"/&gt;
 *         &lt;element ref="{}visao"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "capacidadeMax",
    "codigoCategoriaProduto",
    "codigoGrupoProduto",
    "capacidadeMin",
    "capacidadeMaxContract",
    "codigoProduto",
    "data",
    "dataInicioVigenciaGrupoProduto",
    "habilitarRestricao",
    "id",
    "idElo",
    "visao"
})
@XmlRootElement(name = "capacidadeEstocagemMaxMin")
public class CapacidadeEstocagemMaxMin {

    protected BigDecimal capacidadeMax;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoCategoriaProduto;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoGrupoProduto;
    protected BigDecimal capacidadeMin;
    protected BigDecimal capacidadeMaxContract;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoProduto;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar data;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataInicioVigenciaGrupoProduto;
    protected boolean habilitarRestricao;
    @XmlElement(required = true)
    protected Id id;
    @XmlElement(required = true)
    protected BigInteger idElo;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String visao;

    /**
     * Gets the value of the capacidadeMax property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getCapacidadeMax() {
        return capacidadeMax;
    }

    /**
     * Sets the value of the capacidadeMax property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setCapacidadeMax(BigDecimal value) {
        this.capacidadeMax = value;
    }

    /**
     * Gets the value of the codigoCategoriaProduto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoCategoriaProduto() {
        return codigoCategoriaProduto;
    }

    /**
     * Sets the value of the codigoCategoriaProduto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoCategoriaProduto(String value) {
        this.codigoCategoriaProduto = value;
    }

    /**
     * Gets the value of the codigoGrupoProduto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoGrupoProduto() {
        return codigoGrupoProduto;
    }

    /**
     * Sets the value of the codigoGrupoProduto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoGrupoProduto(String value) {
        this.codigoGrupoProduto = value;
    }

    /**
     * Gets the value of the capacidadeMin property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getCapacidadeMin() {
        return capacidadeMin;
    }

    /**
     * Sets the value of the capacidadeMin property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setCapacidadeMin(BigDecimal value) {
        this.capacidadeMin = value;
    }

    /**
     * Gets the value of the capacidadeMaxContract property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getCapacidadeMaxContract() {
        return capacidadeMaxContract;
    }

    /**
     * Sets the value of the capacidadeMaxContract property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setCapacidadeMaxContract(BigDecimal value) {
        this.capacidadeMaxContract = value;
    }

    /**
     * Gets the value of the codigoProduto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoProduto() {
        return codigoProduto;
    }

    /**
     * Sets the value of the codigoProduto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoProduto(String value) {
        this.codigoProduto = value;
    }

    /**
     * Gets the value of the data property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setData(XMLGregorianCalendar value) {
        this.data = value;
    }

    /**
     * Gets the value of the dataInicioVigenciaGrupoProduto property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataInicioVigenciaGrupoProduto() {
        return dataInicioVigenciaGrupoProduto;
    }

    /**
     * Sets the value of the dataInicioVigenciaGrupoProduto property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataInicioVigenciaGrupoProduto(XMLGregorianCalendar value) {
        this.dataInicioVigenciaGrupoProduto = value;
    }

    /**
     * Gets the value of the habilitarRestricao property.
     *
     */
    public boolean isHabilitarRestricao() {
        return habilitarRestricao;
    }

    /**
     * Sets the value of the habilitarRestricao property.
     *
     */
    public void setHabilitarRestricao(boolean value) {
        this.habilitarRestricao = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link Id }
     *
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link Id }
     *
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the idElo property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getIdElo() {
        return idElo;
    }

    /**
     * Sets the value of the idElo property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setIdElo(BigInteger value) {
        this.idElo = value;
    }

    /**
     * Gets the value of the visao property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVisao() {
        return visao;
    }

    /**
     * Sets the value of the visao property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVisao(String value) {
        this.visao = value;
    }

}
