//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.22 at 08:27:36 PM UTC
//


package inteli.sudeste;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}apoio"/&gt;
 *         &lt;element ref="{}cadeia"/&gt;
 *         &lt;element ref="{}condensadores"/&gt;
 *         &lt;element ref="{}controleQualidadeSequenciaIntermediario"/&gt;
 *         &lt;element ref="{}demanda"/&gt;
 *         &lt;element ref="{}embarques"/&gt;
 *         &lt;element ref="{}fluxo"/&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}produto"/&gt;
 *         &lt;element ref="{}propriedade"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "apoio",
    "cadeia",
    "condensadores",
    "controleQualidadeSequenciaIntermediario",
    "demanda",
    "embarques",
    "fluxo",
    "id",
    "produto",
    "propriedade"
})
@XmlRootElement(name = "cenario")
public class Cenario {

    @XmlElement(required = true)
    protected Apoio apoio;
    @XmlElement(required = true)
    protected Cadeia cadeia;
    @XmlElement(required = true)
    protected Condensadores condensadores;
    @XmlElement(required = true)
    protected ControleQualidadeSequenciaIntermediario controleQualidadeSequenciaIntermediario;
    @XmlElement(required = true)
    protected Demanda demanda;
    @XmlElement(required = true)
    protected Embarques embarques;
    @XmlElement(required = true)
    protected Fluxo fluxo;
    @XmlElement(required = true)
    protected Id id;
    @XmlElement(required = true)
    protected Produto produto;
    @XmlElement(required = true)
    protected Propriedade propriedade;

    /**
     * Gets the value of the apoio property.
     *
     * @return
     *     possible object is
     *     {@link Apoio }
     *
     */
    public Apoio getApoio() {
        return apoio;
    }

    /**
     * Sets the value of the apoio property.
     *
     * @param value
     *     allowed object is
     *     {@link Apoio }
     *
     */
    public void setApoio(Apoio value) {
        this.apoio = value;
    }

    /**
     * Gets the value of the cadeia property.
     *
     * @return
     *     possible object is
     *     {@link Cadeia }
     *
     */
    public Cadeia getCadeia() {
        return cadeia;
    }

    /**
     * Sets the value of the cadeia property.
     *
     * @param value
     *     allowed object is
     *     {@link Cadeia }
     *
     */
    public void setCadeia(Cadeia value) {
        this.cadeia = value;
    }

    /**
     * Gets the value of the condensadores property.
     *
     * @return
     *     possible object is
     *     {@link Condensadores }
     *
     */
    public Condensadores getCondensadores() {
        return condensadores;
    }

    /**
     * Sets the value of the condensadores property.
     *
     * @param value
     *     allowed object is
     *     {@link Condensadores }
     *
     */
    public void setCondensadores(Condensadores value) {
        this.condensadores = value;
    }

    /**
     * Gets the value of the controleQualidadeSequenciaIntermediario property.
     *
     * @return
     *     possible object is
     *     {@link ControleQualidadeSequenciaIntermediario }
     *
     */
    public ControleQualidadeSequenciaIntermediario getControleQualidadeSequenciaIntermediario() {
        return controleQualidadeSequenciaIntermediario;
    }

    /**
     * Sets the value of the controleQualidadeSequenciaIntermediario property.
     *
     * @param value
     *     allowed object is
     *     {@link ControleQualidadeSequenciaIntermediario }
     *
     */
    public void setControleQualidadeSequenciaIntermediario(ControleQualidadeSequenciaIntermediario value) {
        this.controleQualidadeSequenciaIntermediario = value;
    }

    /**
     * Gets the value of the demanda property.
     *
     * @return
     *     possible object is
     *     {@link Demanda }
     *
     */
    public Demanda getDemanda() {
        return demanda;
    }

    /**
     * Sets the value of the demanda property.
     *
     * @param value
     *     allowed object is
     *     {@link Demanda }
     *
     */
    public void setDemanda(Demanda value) {
        this.demanda = value;
    }

    /**
     * Gets the value of the embarques property.
     *
     * @return
     *     possible object is
     *     {@link Embarques }
     *
     */
    public Embarques getEmbarques() {
        return embarques;
    }

    /**
     * Sets the value of the embarques property.
     *
     * @param value
     *     allowed object is
     *     {@link Embarques }
     *
     */
    public void setEmbarques(Embarques value) {
        this.embarques = value;
    }

    /**
     * Gets the value of the fluxo property.
     *
     * @return
     *     possible object is
     *     {@link Fluxo }
     *
     */
    public Fluxo getFluxo() {
        return fluxo;
    }

    /**
     * Sets the value of the fluxo property.
     *
     * @param value
     *     allowed object is
     *     {@link Fluxo }
     *
     */
    public void setFluxo(Fluxo value) {
        this.fluxo = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link Id }
     *
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link Id }
     *
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the produto property.
     *
     * @return
     *     possible object is
     *     {@link Produto }
     *
     */
    public Produto getProduto() {
        return produto;
    }

    /**
     * Sets the value of the produto property.
     *
     * @param value
     *     allowed object is
     *     {@link Produto }
     *
     */
    public void setProduto(Produto value) {
        this.produto = value;
    }

    /**
     * Gets the value of the propriedade property.
     *
     * @return
     *     possible object is
     *     {@link Propriedade }
     *
     */
    public Propriedade getPropriedade() {
        return propriedade;
    }

    /**
     * Sets the value of the propriedade property.
     *
     * @param value
     *     allowed object is
     *     {@link Propriedade }
     *
     */
    public void setPropriedade(Propriedade value) {
        this.propriedade = value;
    }

}
