//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 08:27:36 PM UTC 
//


package inteli.sudeste;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}tipoElo"/&gt;
 *         &lt;element ref="{}codigoCalendario" minOccurs="0"/&gt;
 *         &lt;element ref="{}codigoCliente"/&gt;
 *         &lt;element ref="{}codigoEscritorio" minOccurs="0"/&gt;
 *         &lt;element ref="{}codigoMercado"/&gt;
 *         &lt;element ref="{}codigoPais" minOccurs="0"/&gt;
 *         &lt;element ref="{}codigoRegiao" minOccurs="0"/&gt;
 *         &lt;element ref="{}descricao"/&gt;
 *         &lt;element ref="{}grupoCliente" minOccurs="0"/&gt;
 *         &lt;element ref="{}indicadorPrioridadeAtendimento"/&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element ref="{}indicePercentualRetornoFino"/&gt;
 *           &lt;element ref="{}quantidadeMaximaRetornoFino"/&gt;
 *           &lt;element ref="{}quantidadeMinimaRetornoFino"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element ref="{}tempoPadraoOperacao"/&gt;
 *         &lt;element ref="{}unidadeFederativa" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "tipoElo",
    "codigoCalendario",
    "codigoCliente",
    "codigoEscritorio",
    "codigoMercado",
    "codigoPais",
    "codigoRegiao",
    "descricao",
    "grupoCliente",
    "indicadorPrioridadeAtendimento",
    "indicePercentualRetornoFino",
    "quantidadeMaximaRetornoFino",
    "quantidadeMinimaRetornoFino",
    "tempoPadraoOperacao",
    "unidadeFederativa"
})
@XmlRootElement(name = "clienteAPS")
public class ClienteAPS {

    @XmlElement(required = true)
    protected Id id;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tipoElo;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoCalendario;
    @XmlElement(required = true)
    protected String codigoCliente;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoEscritorio;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoMercado;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoPais;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoRegiao;
    @XmlElement(required = true)
    protected String descricao;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String grupoCliente;
    @XmlElement(required = true)
    protected BigInteger indicadorPrioridadeAtendimento;
    protected BigDecimal indicePercentualRetornoFino;
    protected BigDecimal quantidadeMaximaRetornoFino;
    protected BigDecimal quantidadeMinimaRetornoFino;
    @XmlElement(required = true)
    protected BigDecimal tempoPadraoOperacao;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String unidadeFederativa;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the tipoElo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoElo() {
        return tipoElo;
    }

    /**
     * Sets the value of the tipoElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoElo(String value) {
        this.tipoElo = value;
    }

    /**
     * Gets the value of the codigoCalendario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCalendario() {
        return codigoCalendario;
    }

    /**
     * Sets the value of the codigoCalendario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCalendario(String value) {
        this.codigoCalendario = value;
    }

    /**
     * Gets the value of the codigoCliente property.
     * 
     * @return
     *     {@link String }
     *     
     */
    public String getCodigoCliente() {
        return codigoCliente;
    }

    /**
     * Sets the value of the codigoCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCliente(String value) {
        this.codigoCliente = value;
    }

    /**
     * Gets the value of the codigoEscritorio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoEscritorio() {
        return codigoEscritorio;
    }

    /**
     * Sets the value of the codigoEscritorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoEscritorio(String value) {
        this.codigoEscritorio = value;
    }

    /**
     * Gets the value of the codigoMercado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoMercado() {
        return codigoMercado;
    }

    /**
     * Sets the value of the codigoMercado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoMercado(String value) {
        this.codigoMercado = value;
    }

    /**
     * Gets the value of the codigoPais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoPais() {
        return codigoPais;
    }

    /**
     * Sets the value of the codigoPais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoPais(String value) {
        this.codigoPais = value;
    }

    /**
     * Gets the value of the codigoRegiao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoRegiao() {
        return codigoRegiao;
    }

    /**
     * Sets the value of the codigoRegiao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoRegiao(String value) {
        this.codigoRegiao = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the grupoCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrupoCliente() {
        return grupoCliente;
    }

    /**
     * Sets the value of the grupoCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrupoCliente(String value) {
        this.grupoCliente = value;
    }

    /**
     * Gets the value of the indicadorPrioridadeAtendimento property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndicadorPrioridadeAtendimento() {
        return indicadorPrioridadeAtendimento;
    }

    /**
     * Sets the value of the indicadorPrioridadeAtendimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndicadorPrioridadeAtendimento(BigInteger value) {
        this.indicadorPrioridadeAtendimento = value;
    }

    /**
     * Gets the value of the indicePercentualRetornoFino property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIndicePercentualRetornoFino() {
        return indicePercentualRetornoFino;
    }

    /**
     * Sets the value of the indicePercentualRetornoFino property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIndicePercentualRetornoFino(BigDecimal value) {
        this.indicePercentualRetornoFino = value;
    }

    /**
     * Gets the value of the quantidadeMaximaRetornoFino property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeMaximaRetornoFino() {
        return quantidadeMaximaRetornoFino;
    }

    /**
     * Sets the value of the quantidadeMaximaRetornoFino property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeMaximaRetornoFino(BigDecimal value) {
        this.quantidadeMaximaRetornoFino = value;
    }

    /**
     * Gets the value of the quantidadeMinimaRetornoFino property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeMinimaRetornoFino() {
        return quantidadeMinimaRetornoFino;
    }

    /**
     * Sets the value of the quantidadeMinimaRetornoFino property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeMinimaRetornoFino(BigDecimal value) {
        this.quantidadeMinimaRetornoFino = value;
    }

    /**
     * Gets the value of the tempoPadraoOperacao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTempoPadraoOperacao() {
        return tempoPadraoOperacao;
    }

    /**
     * Sets the value of the tempoPadraoOperacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTempoPadraoOperacao(BigDecimal value) {
        this.tempoPadraoOperacao = value;
    }

    /**
     * Gets the value of the unidadeFederativa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnidadeFederativa() {
        return unidadeFederativa;
    }

    /**
     * Sets the value of the unidadeFederativa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnidadeFederativa(String value) {
        this.unidadeFederativa = value;
    }

}
