//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.22 at 08:27:36 PM UTC
//


package inteli.sudeste;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}alocacoesAPS"/&gt;
 *         &lt;element ref="{}chavesDemandaAPS"/&gt;
 *         &lt;element ref="{}demandasAPS"/&gt;
 *         &lt;element ref="{}detalheOrdemProcessoAsia"/&gt;
 *         &lt;element ref="{}detalheOrdensServicoAsia"/&gt;
 *         &lt;element ref="{}embarquesAsia"/&gt;
 *         &lt;element ref="{}fixacaoPrevisoesAgregadasAsia"/&gt;
 *         &lt;element ref="{}fixacoesAtendimentos"/&gt;
 *         &lt;element ref="{}incotermsAPS"/&gt;
 *         &lt;element ref="{}intakesAPS"/&gt;
 *         &lt;element ref="{}orcamentosAPS"/&gt;
 *         &lt;element ref="{}ordemProcessoAsia"/&gt;
 *         &lt;element ref="{}ordensServicoAsia"/&gt;
 *         &lt;element ref="{}ordensVendaAPS"/&gt;
 *         &lt;element ref="{}previsoesAgregadas"/&gt;
 *         &lt;element ref="{}previsoesAgregadasAsia"/&gt;
 *         &lt;element ref="{}previsoesCarregamentos"/&gt;
 *         &lt;element ref="{}producoesBlendCadeiaEstendida"/&gt;
 *         &lt;element ref="{}produtoAlternativoAsia"/&gt;
 *         &lt;element ref="{}podutosBlendAPS"/&gt;
 *         &lt;element ref="{}programacoesDemandaFeed"/&gt;
 *         &lt;element ref="{}programacoesVenda"/&gt;
 *         &lt;element ref="{}simplificacoesCadeia"/&gt;
 *         &lt;element ref="{}tiposDeVendaAPS"/&gt;
 *         &lt;element ref="{}vendasRealizadaAPS"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alocacoesAPS",
    "chavesDemandaAPS",
    "demandasAPS",
    "detalheOrdemProcessoAsia",
    "detalheOrdensServicoAsia",
    "embarquesAsia",
    "fixacaoPrevisoesAgregadasAsia",
    "fixacoesAtendimentos",
    "incotermsAPS",
    "intakesAPS",
    "orcamentosAPS",
    "ordemProcessoAsia",
    "ordensServicoAsia",
    "ordensVendaAPS",
    "previsoesAgregadas",
    "previsoesAgregadasAsia",
    "previsoesCarregamentos",
    "producoesBlendCadeiaEstendida",
    "produtoAlternativoAsia",
    "podutosBlendAPS",
    "programacoesDemandaFeed",
    "programacoesVenda",
    "simplificacoesCadeia",
    "tiposDeVendaAPS",
    "vendasRealizadaAPS"
})
@XmlRootElement(name = "demanda")
public class Demanda {

    @XmlElement(required = true)
    protected AlocacoesAPS alocacoesAPS;
    @XmlElement(required = true)
    protected ChavesDemandaAPS chavesDemandaAPS;
    @XmlElement(required = true)
    protected DemandasAPS demandasAPS;
    @XmlElement(required = true)
    protected DetalheOrdemProcessoAsia detalheOrdemProcessoAsia;
    @XmlElement(required = true)
    protected DetalheOrdensServicoAsia detalheOrdensServicoAsia;
    @XmlElement(required = true)
    protected EmbarquesAsia embarquesAsia;
    @XmlElement(required = true)
    protected FixacaoPrevisoesAgregadasAsia fixacaoPrevisoesAgregadasAsia;
    @XmlElement(required = true)
    protected FixacoesAtendimentos fixacoesAtendimentos;
    @XmlElement(required = true)
    protected IncotermsAPS incotermsAPS;
    @XmlElement(required = true)
    protected IntakesAPS intakesAPS;
    @XmlElement(required = true)
    protected OrcamentosAPS orcamentosAPS;
    @XmlElement(required = true)
    protected OrdemProcessoAsia ordemProcessoAsia;
    @XmlElement(required = true)
    protected OrdensServicoAsia ordensServicoAsia;
    @XmlElement(required = true)
    protected OrdensVendaAPS ordensVendaAPS;
    @XmlElement(required = true)
    protected PrevisoesAgregadas previsoesAgregadas;
    @XmlElement(required = true)
    protected PrevisoesAgregadasAsia previsoesAgregadasAsia;
    @XmlElement(required = true)
    protected PrevisoesCarregamentos previsoesCarregamentos;
    @XmlElement(required = true)
    protected ProducoesBlendCadeiaEstendida producoesBlendCadeiaEstendida;
    @XmlElement(required = true)
    protected ProdutoAlternativoAsia produtoAlternativoAsia;
    @XmlElement(required = true)
    protected PodutosBlendAPS podutosBlendAPS;
    @XmlElement(required = true)
    protected ProgramacoesDemandaFeed programacoesDemandaFeed;
    @XmlElement(required = true)
    protected ProgramacoesVenda programacoesVenda;
    @XmlElement(required = true)
    protected SimplificacoesCadeia simplificacoesCadeia;
    @XmlElement(required = true)
    protected TiposDeVendaAPS tiposDeVendaAPS;
    @XmlElement(required = true)
    protected VendasRealizadaAPS vendasRealizadaAPS;

    /**
     * Gets the value of the alocacoesAPS property.
     *
     * @return
     *     possible object is
     *     {@link AlocacoesAPS }
     *
     */
    public AlocacoesAPS getAlocacoesAPS() {
        return alocacoesAPS;
    }

    /**
     * Sets the value of the alocacoesAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link AlocacoesAPS }
     *
     */
    public void setAlocacoesAPS(AlocacoesAPS value) {
        this.alocacoesAPS = value;
    }

    /**
     * Gets the value of the chavesDemandaAPS property.
     *
     * @return
     *     possible object is
     *     {@link ChavesDemandaAPS }
     *
     */
    public ChavesDemandaAPS getChavesDemandaAPS() {
        return chavesDemandaAPS;
    }

    /**
     * Sets the value of the chavesDemandaAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link ChavesDemandaAPS }
     *
     */
    public void setChavesDemandaAPS(ChavesDemandaAPS value) {
        this.chavesDemandaAPS = value;
    }

    /**
     * Gets the value of the demandasAPS property.
     *
     * @return
     *     possible object is
     *     {@link DemandasAPS }
     *
     */
    public DemandasAPS getDemandasAPS() {
        return demandasAPS;
    }

    /**
     * Sets the value of the demandasAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link DemandasAPS }
     *
     */
    public void setDemandasAPS(DemandasAPS value) {
        this.demandasAPS = value;
    }

    /**
     * Gets the value of the detalheOrdemProcessoAsia property.
     *
     * @return
     *     possible object is
     *     {@link DetalheOrdemProcessoAsia }
     *
     */
    public DetalheOrdemProcessoAsia getDetalheOrdemProcessoAsia() {
        return detalheOrdemProcessoAsia;
    }

    /**
     * Sets the value of the detalheOrdemProcessoAsia property.
     *
     * @param value
     *     allowed object is
     *     {@link DetalheOrdemProcessoAsia }
     *
     */
    public void setDetalheOrdemProcessoAsia(DetalheOrdemProcessoAsia value) {
        this.detalheOrdemProcessoAsia = value;
    }

    /**
     * Gets the value of the detalheOrdensServicoAsia property.
     *
     * @return
     *     possible object is
     *     {@link DetalheOrdensServicoAsia }
     *
     */
    public DetalheOrdensServicoAsia getDetalheOrdensServicoAsia() {
        return detalheOrdensServicoAsia;
    }

    /**
     * Sets the value of the detalheOrdensServicoAsia property.
     *
     * @param value
     *     allowed object is
     *     {@link DetalheOrdensServicoAsia }
     *
     */
    public void setDetalheOrdensServicoAsia(DetalheOrdensServicoAsia value) {
        this.detalheOrdensServicoAsia = value;
    }

    /**
     * Gets the value of the embarquesAsia property.
     *
     * @return
     *     possible object is
     *     {@link EmbarquesAsia }
     *
     */
    public EmbarquesAsia getEmbarquesAsia() {
        return embarquesAsia;
    }

    /**
     * Sets the value of the embarquesAsia property.
     *
     * @param value
     *     allowed object is
     *     {@link EmbarquesAsia }
     *
     */
    public void setEmbarquesAsia(EmbarquesAsia value) {
        this.embarquesAsia = value;
    }

    /**
     * Gets the value of the fixacaoPrevisoesAgregadasAsia property.
     *
     * @return
     *     possible object is
     *     {@link FixacaoPrevisoesAgregadasAsia }
     *
     */
    public FixacaoPrevisoesAgregadasAsia getFixacaoPrevisoesAgregadasAsia() {
        return fixacaoPrevisoesAgregadasAsia;
    }

    /**
     * Sets the value of the fixacaoPrevisoesAgregadasAsia property.
     *
     * @param value
     *     allowed object is
     *     {@link FixacaoPrevisoesAgregadasAsia }
     *
     */
    public void setFixacaoPrevisoesAgregadasAsia(FixacaoPrevisoesAgregadasAsia value) {
        this.fixacaoPrevisoesAgregadasAsia = value;
    }

    /**
     * Gets the value of the fixacoesAtendimentos property.
     *
     * @return
     *     possible object is
     *     {@link FixacoesAtendimentos }
     *
     */
    public FixacoesAtendimentos getFixacoesAtendimentos() {
        return fixacoesAtendimentos;
    }

    /**
     * Sets the value of the fixacoesAtendimentos property.
     *
     * @param value
     *     allowed object is
     *     {@link FixacoesAtendimentos }
     *
     */
    public void setFixacoesAtendimentos(FixacoesAtendimentos value) {
        this.fixacoesAtendimentos = value;
    }

    /**
     * Gets the value of the incotermsAPS property.
     *
     * @return
     *     possible object is
     *     {@link IncotermsAPS }
     *
     */
    public IncotermsAPS getIncotermsAPS() {
        return incotermsAPS;
    }

    /**
     * Sets the value of the incotermsAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link IncotermsAPS }
     *
     */
    public void setIncotermsAPS(IncotermsAPS value) {
        this.incotermsAPS = value;
    }

    /**
     * Gets the value of the intakesAPS property.
     *
     * @return
     *     possible object is
     *     {@link IntakesAPS }
     *
     */
    public IntakesAPS getIntakesAPS() {
        return intakesAPS;
    }

    /**
     * Sets the value of the intakesAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link IntakesAPS }
     *
     */
    public void setIntakesAPS(IntakesAPS value) {
        this.intakesAPS = value;
    }

    /**
     * Gets the value of the orcamentosAPS property.
     *
     * @return
     *     possible object is
     *     {@link OrcamentosAPS }
     *
     */
    public OrcamentosAPS getOrcamentosAPS() {
        return orcamentosAPS;
    }

    /**
     * Sets the value of the orcamentosAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link OrcamentosAPS }
     *
     */
    public void setOrcamentosAPS(OrcamentosAPS value) {
        this.orcamentosAPS = value;
    }

    /**
     * Gets the value of the ordemProcessoAsia property.
     *
     * @return
     *     possible object is
     *     {@link OrdemProcessoAsia }
     *
     */
    public OrdemProcessoAsia getOrdemProcessoAsia() {
        return ordemProcessoAsia;
    }

    /**
     * Sets the value of the ordemProcessoAsia property.
     *
     * @param value
     *     allowed object is
     *     {@link OrdemProcessoAsia }
     *
     */
    public void setOrdemProcessoAsia(OrdemProcessoAsia value) {
        this.ordemProcessoAsia = value;
    }

    /**
     * Gets the value of the ordensServicoAsia property.
     *
     * @return
     *     possible object is
     *     {@link OrdensServicoAsia }
     *
     */
    public OrdensServicoAsia getOrdensServicoAsia() {
        return ordensServicoAsia;
    }

    /**
     * Sets the value of the ordensServicoAsia property.
     *
     * @param value
     *     allowed object is
     *     {@link OrdensServicoAsia }
     *
     */
    public void setOrdensServicoAsia(OrdensServicoAsia value) {
        this.ordensServicoAsia = value;
    }

    /**
     * Gets the value of the ordensVendaAPS property.
     *
     * @return
     *     possible object is
     *     {@link OrdensVendaAPS }
     *
     */
    public OrdensVendaAPS getOrdensVendaAPS() {
        return ordensVendaAPS;
    }

    /**
     * Sets the value of the ordensVendaAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link OrdensVendaAPS }
     *
     */
    public void setOrdensVendaAPS(OrdensVendaAPS value) {
        this.ordensVendaAPS = value;
    }

    /**
     * Gets the value of the previsoesAgregadas property.
     *
     * @return
     *     possible object is
     *     {@link PrevisoesAgregadas }
     *
     */
    public PrevisoesAgregadas getPrevisoesAgregadas() {
        return previsoesAgregadas;
    }

    /**
     * Sets the value of the previsoesAgregadas property.
     *
     * @param value
     *     allowed object is
     *     {@link PrevisoesAgregadas }
     *
     */
    public void setPrevisoesAgregadas(PrevisoesAgregadas value) {
        this.previsoesAgregadas = value;
    }

    /**
     * Gets the value of the previsoesAgregadasAsia property.
     *
     * @return
     *     possible object is
     *     {@link PrevisoesAgregadasAsia }
     *
     */
    public PrevisoesAgregadasAsia getPrevisoesAgregadasAsia() {
        return previsoesAgregadasAsia;
    }

    /**
     * Sets the value of the previsoesAgregadasAsia property.
     *
     * @param value
     *     allowed object is
     *     {@link PrevisoesAgregadasAsia }
     *
     */
    public void setPrevisoesAgregadasAsia(PrevisoesAgregadasAsia value) {
        this.previsoesAgregadasAsia = value;
    }

    /**
     * Gets the value of the previsoesCarregamentos property.
     *
     * @return
     *     possible object is
     *     {@link PrevisoesCarregamentos }
     *
     */
    public PrevisoesCarregamentos getPrevisoesCarregamentos() {
        return previsoesCarregamentos;
    }

    /**
     * Sets the value of the previsoesCarregamentos property.
     *
     * @param value
     *     allowed object is
     *     {@link PrevisoesCarregamentos }
     *
     */
    public void setPrevisoesCarregamentos(PrevisoesCarregamentos value) {
        this.previsoesCarregamentos = value;
    }

    /**
     * Gets the value of the producoesBlendCadeiaEstendida property.
     *
     * @return
     *     possible object is
     *     {@link ProducoesBlendCadeiaEstendida }
     *
     */
    public ProducoesBlendCadeiaEstendida getProducoesBlendCadeiaEstendida() {
        return producoesBlendCadeiaEstendida;
    }

    /**
     * Sets the value of the producoesBlendCadeiaEstendida property.
     *
     * @param value
     *     allowed object is
     *     {@link ProducoesBlendCadeiaEstendida }
     *
     */
    public void setProducoesBlendCadeiaEstendida(ProducoesBlendCadeiaEstendida value) {
        this.producoesBlendCadeiaEstendida = value;
    }

    /**
     * Gets the value of the produtoAlternativoAsia property.
     *
     * @return
     *     possible object is
     *     {@link ProdutoAlternativoAsia }
     *
     */
    public ProdutoAlternativoAsia getProdutoAlternativoAsia() {
        return produtoAlternativoAsia;
    }

    /**
     * Sets the value of the produtoAlternativoAsia property.
     *
     * @param value
     *     allowed object is
     *     {@link ProdutoAlternativoAsia }
     *
     */
    public void setProdutoAlternativoAsia(ProdutoAlternativoAsia value) {
        this.produtoAlternativoAsia = value;
    }

    /**
     * Gets the value of the podutosBlendAPS property.
     *
     * @return
     *     possible object is
     *     {@link PodutosBlendAPS }
     *
     */
    public PodutosBlendAPS getPodutosBlendAPS() {
        return podutosBlendAPS;
    }

    /**
     * Sets the value of the podutosBlendAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link PodutosBlendAPS }
     *
     */
    public void setPodutosBlendAPS(PodutosBlendAPS value) {
        this.podutosBlendAPS = value;
    }

    /**
     * Gets the value of the programacoesDemandaFeed property.
     *
     * @return
     *     possible object is
     *     {@link ProgramacoesDemandaFeed }
     *
     */
    public ProgramacoesDemandaFeed getProgramacoesDemandaFeed() {
        return programacoesDemandaFeed;
    }

    /**
     * Sets the value of the programacoesDemandaFeed property.
     *
     * @param value
     *     allowed object is
     *     {@link ProgramacoesDemandaFeed }
     *
     */
    public void setProgramacoesDemandaFeed(ProgramacoesDemandaFeed value) {
        this.programacoesDemandaFeed = value;
    }

    /**
     * Gets the value of the programacoesVenda property.
     *
     * @return
     *     possible object is
     *     {@link ProgramacoesVenda }
     *
     */
    public ProgramacoesVenda getProgramacoesVenda() {
        return programacoesVenda;
    }

    /**
     * Sets the value of the programacoesVenda property.
     *
     * @param value
     *     allowed object is
     *     {@link ProgramacoesVenda }
     *
     */
    public void setProgramacoesVenda(ProgramacoesVenda value) {
        this.programacoesVenda = value;
    }

    /**
     * Gets the value of the simplificacoesCadeia property.
     *
     * @return
     *     possible object is
     *     {@link SimplificacoesCadeia }
     *
     */
    public SimplificacoesCadeia getSimplificacoesCadeia() {
        return simplificacoesCadeia;
    }

    /**
     * Sets the value of the simplificacoesCadeia property.
     *
     * @param value
     *     allowed object is
     *     {@link SimplificacoesCadeia }
     *
     */
    public void setSimplificacoesCadeia(SimplificacoesCadeia value) {
        this.simplificacoesCadeia = value;
    }

    /**
     * Gets the value of the tiposDeVendaAPS property.
     *
     * @return
     *     possible object is
     *     {@link TiposDeVendaAPS }
     *
     */
    public TiposDeVendaAPS getTiposDeVendaAPS() {
        return tiposDeVendaAPS;
    }

    /**
     * Sets the value of the tiposDeVendaAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link TiposDeVendaAPS }
     *
     */
    public void setTiposDeVendaAPS(TiposDeVendaAPS value) {
        this.tiposDeVendaAPS = value;
    }

    /**
     * Gets the value of the vendasRealizadaAPS property.
     *
     * @return
     *     possible object is
     *     {@link VendasRealizadaAPS }
     *
     */
    public VendasRealizadaAPS getVendasRealizadaAPS() {
        return vendasRealizadaAPS;
    }

    /**
     * Sets the value of the vendasRealizadaAPS property.
     *
     * @param value
     *     allowed object is
     *     {@link VendasRealizadaAPS }
     *
     */
    public void setVendasRealizadaAPS(VendasRealizadaAPS value) {
        this.vendasRealizadaAPS = value;
    }

}
