//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 08:27:36 PM UTC 
//


package inteli.sudeste;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}codigoProduto"/&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element ref="{}codigoProdutoDestino"/&gt;
 *           &lt;element ref="{}codigoSubmodal"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element ref="{}data"/&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}idCliente" minOccurs="0"/&gt;
 *         &lt;element ref="{}idEloCadeiaProducao"/&gt;
 *         &lt;element ref="{}idEloOrigem" minOccurs="0"/&gt;
 *         &lt;element ref="{}indicadorEstoqueInicial"/&gt;
 *         &lt;element ref="{}quantidade"/&gt;
 *         &lt;element ref="{}quantidadeTotal"/&gt;
 *         &lt;element ref="{}sequencia"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoProduto",
    "codigoProdutoDestino",
    "codigoSubmodal",
    "data",
    "id",
    "idCliente",
    "idEloCadeiaProducao",
    "idEloOrigem",
    "indicadorEstoqueInicial",
    "quantidade",
    "quantidadeTotal",
    "sequencia"
})
@XmlRootElement(name = "estoqueInicial")
public class EstoqueInicial {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoProduto;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoProdutoDestino;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoSubmodal;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar data;
    @XmlElement(required = true)
    protected Id id;
    protected BigInteger idCliente;
    @XmlElement(required = true)
    protected BigInteger idEloCadeiaProducao;
    protected BigInteger idEloOrigem;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String indicadorEstoqueInicial;
    @XmlElement(required = true)
    protected BigDecimal quantidade;
    @XmlElement(required = true)
    protected BigDecimal quantidadeTotal;
    @XmlElement(required = true)
    protected BigInteger sequencia;

    /**
     * Gets the value of the codigoProduto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoProduto() {
        return codigoProduto;
    }

    /**
     * Sets the value of the codigoProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoProduto(String value) {
        this.codigoProduto = value;
    }

    /**
     * Gets the value of the codigoProdutoDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoProdutoDestino() {
        return codigoProdutoDestino;
    }

    /**
     * Sets the value of the codigoProdutoDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoProdutoDestino(String value) {
        this.codigoProdutoDestino = value;
    }

    /**
     * Gets the value of the codigoSubmodal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoSubmodal() {
        return codigoSubmodal;
    }

    /**
     * Sets the value of the codigoSubmodal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoSubmodal(String value) {
        this.codigoSubmodal = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setData(XMLGregorianCalendar value) {
        this.data = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the idCliente property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdCliente() {
        return idCliente;
    }

    /**
     * Sets the value of the idCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdCliente(BigInteger value) {
        this.idCliente = value;
    }

    /**
     * Gets the value of the idEloCadeiaProducao property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdEloCadeiaProducao() {
        return idEloCadeiaProducao;
    }

    /**
     * Sets the value of the idEloCadeiaProducao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdEloCadeiaProducao(BigInteger value) {
        this.idEloCadeiaProducao = value;
    }

    /**
     * Gets the value of the idEloOrigem property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdEloOrigem() {
        return idEloOrigem;
    }

    /**
     * Sets the value of the idEloOrigem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdEloOrigem(BigInteger value) {
        this.idEloOrigem = value;
    }

    /**
     * Gets the value of the indicadorEstoqueInicial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorEstoqueInicial() {
        return indicadorEstoqueInicial;
    }

    /**
     * Sets the value of the indicadorEstoqueInicial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorEstoqueInicial(String value) {
        this.indicadorEstoqueInicial = value;
    }

    /**
     * Gets the value of the quantidade property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidade() {
        return quantidade;
    }

    /**
     * Sets the value of the quantidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidade(BigDecimal value) {
        this.quantidade = value;
    }

    /**
     * Gets the value of the quantidadeTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeTotal() {
        return quantidadeTotal;
    }

    /**
     * Sets the value of the quantidadeTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeTotal(BigDecimal value) {
        this.quantidadeTotal = value;
    }

    /**
     * Gets the value of the sequencia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequencia() {
        return sequencia;
    }

    /**
     * Sets the value of the sequencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequencia(BigInteger value) {
        this.sequencia = value;
    }

}
