//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 08:27:36 PM UTC 
//


package inteli.sudeste;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}composicoesExpedicao"/&gt;
 *         &lt;element ref="{}curvasRisco"/&gt;
 *         &lt;element ref="{}disponibilidadeMovimentacoes"/&gt;
 *         &lt;element ref="{}disponibilidadesTransporte"/&gt;
 *         &lt;element ref="{}faixasRisco"/&gt;
 *         &lt;element ref="{}fatoresManuseio"/&gt;
 *         &lt;element ref="{}fracoesLoteProduto"/&gt;
 *         &lt;element ref="{}perdasMassa"/&gt;
 *         &lt;element ref="{}qualidadesTransferenciaAPS"/&gt;
 *         &lt;element ref="{}riscosMaximo"/&gt;
 *         &lt;element ref="{}submodaisTransporte"/&gt;
 *         &lt;element ref="{}subRedesTransporte"/&gt;
 *         &lt;element ref="{}tiposModalTransporte"/&gt;
 *         &lt;element ref="{}trechosSubRedeTransporte"/&gt;
 *         &lt;element ref="{}trechosTransporte"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "composicoesExpedicao",
    "curvasRisco",
    "disponibilidadeMovimentacoes",
    "disponibilidadesTransporte",
    "faixasRisco",
    "fatoresManuseio",
    "fracoesLoteProduto",
    "perdasMassa",
    "qualidadesTransferenciaAPS",
    "riscosMaximo",
    "submodaisTransporte",
    "subRedesTransporte",
    "tiposModalTransporte",
    "trechosSubRedeTransporte",
    "trechosTransporte"
})
@XmlRootElement(name = "fluxo")
public class Fluxo {

    @XmlElement(required = true)
    protected ComposicoesExpedicao composicoesExpedicao;
    @XmlElement(required = true)
    protected CurvasRisco curvasRisco;
    @XmlElement(required = true)
    protected DisponibilidadeMovimentacoes disponibilidadeMovimentacoes;
    @XmlElement(required = true)
    protected DisponibilidadesTransporte disponibilidadesTransporte;
    @XmlElement(required = true)
    protected FaixasRisco faixasRisco;
    @XmlElement(required = true)
    protected FatoresManuseio fatoresManuseio;
    @XmlElement(required = true)
    protected FracoesLoteProduto fracoesLoteProduto;
    @XmlElement(required = true)
    protected PerdasMassa perdasMassa;
    @XmlElement(required = true)
    protected QualidadesTransferenciaAPS qualidadesTransferenciaAPS;
    @XmlElement(required = true)
    protected RiscosMaximo riscosMaximo;
    @XmlElement(required = true)
    protected SubmodaisTransporte submodaisTransporte;
    @XmlElement(required = true)
    protected SubRedesTransporte subRedesTransporte;
    @XmlElement(required = true)
    protected TiposModalTransporte tiposModalTransporte;
    @XmlElement(required = true)
    protected TrechosSubRedeTransporte trechosSubRedeTransporte;
    @XmlElement(required = true)
    protected TrechosTransporte trechosTransporte;

    /**
     * Gets the value of the composicoesExpedicao property.
     * 
     * @return
     *     possible object is
     *     {@link ComposicoesExpedicao }
     *     
     */
    public ComposicoesExpedicao getComposicoesExpedicao() {
        return composicoesExpedicao;
    }

    /**
     * Sets the value of the composicoesExpedicao property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComposicoesExpedicao }
     *     
     */
    public void setComposicoesExpedicao(ComposicoesExpedicao value) {
        this.composicoesExpedicao = value;
    }

    /**
     * Gets the value of the curvasRisco property.
     * 
     * @return
     *     possible object is
     *     {@link CurvasRisco }
     *     
     */
    public CurvasRisco getCurvasRisco() {
        return curvasRisco;
    }

    /**
     * Sets the value of the curvasRisco property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurvasRisco }
     *     
     */
    public void setCurvasRisco(CurvasRisco value) {
        this.curvasRisco = value;
    }

    /**
     * Gets the value of the disponibilidadeMovimentacoes property.
     * 
     * @return
     *     possible object is
     *     {@link DisponibilidadeMovimentacoes }
     *     
     */
    public DisponibilidadeMovimentacoes getDisponibilidadeMovimentacoes() {
        return disponibilidadeMovimentacoes;
    }

    /**
     * Sets the value of the disponibilidadeMovimentacoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisponibilidadeMovimentacoes }
     *     
     */
    public void setDisponibilidadeMovimentacoes(DisponibilidadeMovimentacoes value) {
        this.disponibilidadeMovimentacoes = value;
    }

    /**
     * Gets the value of the disponibilidadesTransporte property.
     * 
     * @return
     *     possible object is
     *     {@link DisponibilidadesTransporte }
     *     
     */
    public DisponibilidadesTransporte getDisponibilidadesTransporte() {
        return disponibilidadesTransporte;
    }

    /**
     * Sets the value of the disponibilidadesTransporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisponibilidadesTransporte }
     *     
     */
    public void setDisponibilidadesTransporte(DisponibilidadesTransporte value) {
        this.disponibilidadesTransporte = value;
    }

    /**
     * Gets the value of the faixasRisco property.
     * 
     * @return
     *     possible object is
     *     {@link FaixasRisco }
     *     
     */
    public FaixasRisco getFaixasRisco() {
        return faixasRisco;
    }

    /**
     * Sets the value of the faixasRisco property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaixasRisco }
     *     
     */
    public void setFaixasRisco(FaixasRisco value) {
        this.faixasRisco = value;
    }

    /**
     * Gets the value of the fatoresManuseio property.
     * 
     * @return
     *     possible object is
     *     {@link FatoresManuseio }
     *     
     */
    public FatoresManuseio getFatoresManuseio() {
        return fatoresManuseio;
    }

    /**
     * Sets the value of the fatoresManuseio property.
     * 
     * @param value
     *     allowed object is
     *     {@link FatoresManuseio }
     *     
     */
    public void setFatoresManuseio(FatoresManuseio value) {
        this.fatoresManuseio = value;
    }

    /**
     * Gets the value of the fracoesLoteProduto property.
     * 
     * @return
     *     possible object is
     *     {@link FracoesLoteProduto }
     *     
     */
    public FracoesLoteProduto getFracoesLoteProduto() {
        return fracoesLoteProduto;
    }

    /**
     * Sets the value of the fracoesLoteProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link FracoesLoteProduto }
     *     
     */
    public void setFracoesLoteProduto(FracoesLoteProduto value) {
        this.fracoesLoteProduto = value;
    }

    /**
     * Gets the value of the perdasMassa property.
     * 
     * @return
     *     possible object is
     *     {@link PerdasMassa }
     *     
     */
    public PerdasMassa getPerdasMassa() {
        return perdasMassa;
    }

    /**
     * Sets the value of the perdasMassa property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerdasMassa }
     *     
     */
    public void setPerdasMassa(PerdasMassa value) {
        this.perdasMassa = value;
    }

    /**
     * Gets the value of the qualidadesTransferenciaAPS property.
     * 
     * @return
     *     possible object is
     *     {@link QualidadesTransferenciaAPS }
     *     
     */
    public QualidadesTransferenciaAPS getQualidadesTransferenciaAPS() {
        return qualidadesTransferenciaAPS;
    }

    /**
     * Sets the value of the qualidadesTransferenciaAPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualidadesTransferenciaAPS }
     *     
     */
    public void setQualidadesTransferenciaAPS(QualidadesTransferenciaAPS value) {
        this.qualidadesTransferenciaAPS = value;
    }

    /**
     * Gets the value of the riscosMaximo property.
     * 
     * @return
     *     possible object is
     *     {@link RiscosMaximo }
     *     
     */
    public RiscosMaximo getRiscosMaximo() {
        return riscosMaximo;
    }

    /**
     * Sets the value of the riscosMaximo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiscosMaximo }
     *     
     */
    public void setRiscosMaximo(RiscosMaximo value) {
        this.riscosMaximo = value;
    }

    /**
     * Gets the value of the submodaisTransporte property.
     * 
     * @return
     *     possible object is
     *     {@link SubmodaisTransporte }
     *     
     */
    public SubmodaisTransporte getSubmodaisTransporte() {
        return submodaisTransporte;
    }

    /**
     * Sets the value of the submodaisTransporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmodaisTransporte }
     *     
     */
    public void setSubmodaisTransporte(SubmodaisTransporte value) {
        this.submodaisTransporte = value;
    }

    /**
     * Gets the value of the subRedesTransporte property.
     * 
     * @return
     *     possible object is
     *     {@link SubRedesTransporte }
     *     
     */
    public SubRedesTransporte getSubRedesTransporte() {
        return subRedesTransporte;
    }

    /**
     * Sets the value of the subRedesTransporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubRedesTransporte }
     *     
     */
    public void setSubRedesTransporte(SubRedesTransporte value) {
        this.subRedesTransporte = value;
    }

    /**
     * Gets the value of the tiposModalTransporte property.
     * 
     * @return
     *     possible object is
     *     {@link TiposModalTransporte }
     *     
     */
    public TiposModalTransporte getTiposModalTransporte() {
        return tiposModalTransporte;
    }

    /**
     * Sets the value of the tiposModalTransporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TiposModalTransporte }
     *     
     */
    public void setTiposModalTransporte(TiposModalTransporte value) {
        this.tiposModalTransporte = value;
    }

    /**
     * Gets the value of the trechosSubRedeTransporte property.
     * 
     * @return
     *     possible object is
     *     {@link TrechosSubRedeTransporte }
     *     
     */
    public TrechosSubRedeTransporte getTrechosSubRedeTransporte() {
        return trechosSubRedeTransporte;
    }

    /**
     * Sets the value of the trechosSubRedeTransporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrechosSubRedeTransporte }
     *     
     */
    public void setTrechosSubRedeTransporte(TrechosSubRedeTransporte value) {
        this.trechosSubRedeTransporte = value;
    }

    /**
     * Gets the value of the trechosTransporte property.
     * 
     * @return
     *     possible object is
     *     {@link TrechosTransporte }
     *     
     */
    public TrechosTransporte getTrechosTransporte() {
        return trechosTransporte;
    }

    /**
     * Sets the value of the trechosTransporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrechosTransporte }
     *     
     */
    public void setTrechosTransporte(TrechosTransporte value) {
        this.trechosTransporte = value;
    }

}
