//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.22 at 08:27:36 PM UTC
//


package inteli.sudeste;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{}codigoCategoria"/&gt;
 *         &lt;element ref="{}codigoCategoriaProduto"/&gt;
 *         &lt;element ref="{}codigoEnsaio"/&gt;
 *         &lt;element ref="{}codigoGrandeza"/&gt;
 *         &lt;element ref="{}codigoNaturezaEnsaio"/&gt;
 *         &lt;element ref="{}codigoProduto"/&gt;
 *         &lt;element ref="{}codigoSubCategoria"/&gt;
 *         &lt;element ref="{}codigoSubModal"/&gt;
 *         &lt;element ref="{}dataInicioVigencia"/&gt;
 *         &lt;element ref="{}idCliente"/&gt;
 *         &lt;element ref="{}idEloCadeiaProducao"/&gt;
 *         &lt;element ref="{}idEloCadeiaProducaoDestino"/&gt;
 *         &lt;element ref="{}idEloCadeiaProducaoOrigem"/&gt;
 *         &lt;element ref="{}idEloDestino"/&gt;
 *         &lt;element ref="{}idEloOrigem"/&gt;
 *         &lt;element ref="{}idSubRedeTransporte"/&gt;
 *         &lt;element ref="{}minimina"/&gt;
 *         &lt;element ref="{}sequencia"/&gt;
 *         &lt;element ref="{}visao"/&gt;
 *         &lt;element ref="{}codigo"/&gt;
 *         &lt;element ref="{}codigoGrupo"/&gt;
 *         &lt;element ref="{}dataAssociacao"/&gt;
 *         &lt;element ref="{}dataVigencia"/&gt;
 *         &lt;element ref="{}idBlendagemProduto"/&gt;
 *         &lt;element ref="{}idEloAtende"/&gt;
 *         &lt;element ref="{}idEloCadeia"/&gt;
 *         &lt;element ref="{}idEloCadeiaDestino"/&gt;
 *         &lt;element ref="{}idEloCadeiaOrigem"/&gt;
 *         &lt;element ref="{}idEstoqueInicial"/&gt;
 *         &lt;element ref="{}idMapaAnalise"/&gt;
 *         &lt;element ref="{}idQualidadeTransferenciaAPS"/&gt;
 *         &lt;element ref="{}tipoVisao"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "id")
public class Id {

    @XmlElementRefs({
        @XmlElementRef(name = "codigoCategoria", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "codigoCategoriaProduto", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "codigoEnsaio", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "codigoGrandeza", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "codigoNaturezaEnsaio", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "codigoProduto", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "codigoSubCategoria", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "codigoSubModal", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dataInicioVigencia", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idCliente", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEloCadeiaProducao", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEloCadeiaProducaoDestino", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEloCadeiaProducaoOrigem", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEloDestino", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEloOrigem", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idSubRedeTransporte", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "minimina", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sequencia", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "visao", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "codigo", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "codigoGrupo", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dataAssociacao", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dataVigencia", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idBlendagemProduto", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEloAtende", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEloCadeia", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEloCadeiaDestino", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEloCadeiaOrigem", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idEstoqueInicial", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idMapaAnalise", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "idQualidadeTransferenciaAPS", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tipoVisao", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link String }
     *
     *
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
