//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 08:27:36 PM UTC 
//


package inteli.sudeste;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}dataFimVigencia" minOccurs="0"/&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}qtdeProduto"/&gt;
 *         &lt;element ref="{}tempoFormacao" minOccurs="0"/&gt;
 *         &lt;element ref="{}tipoAtendimento"/&gt;
 *         &lt;element ref="{}unidadeQuantidade"/&gt;
 *         &lt;element ref="{}valorIntervaloTempo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataFimVigencia",
    "id",
    "qtdeProduto",
    "tempoFormacao",
    "tipoAtendimento",
    "unidadeQuantidade",
    "valorIntervaloTempo"
})
@XmlRootElement(name = "pilhaPadrao")
public class PilhaPadrao {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataFimVigencia;
    @XmlElement(required = true)
    protected Id id;
    @XmlElement(required = true)
    protected BigDecimal qtdeProduto;
    protected BigDecimal tempoFormacao;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tipoAtendimento;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String unidadeQuantidade;
    protected BigDecimal valorIntervaloTempo;

    /**
     * Gets the value of the dataFimVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataFimVigencia() {
        return dataFimVigencia;
    }

    /**
     * Sets the value of the dataFimVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataFimVigencia(XMLGregorianCalendar value) {
        this.dataFimVigencia = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the qtdeProduto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQtdeProduto() {
        return qtdeProduto;
    }

    /**
     * Sets the value of the qtdeProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQtdeProduto(BigDecimal value) {
        this.qtdeProduto = value;
    }

    /**
     * Gets the value of the tempoFormacao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTempoFormacao() {
        return tempoFormacao;
    }

    /**
     * Sets the value of the tempoFormacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTempoFormacao(BigDecimal value) {
        this.tempoFormacao = value;
    }

    /**
     * Gets the value of the tipoAtendimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoAtendimento() {
        return tipoAtendimento;
    }

    /**
     * Sets the value of the tipoAtendimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoAtendimento(String value) {
        this.tipoAtendimento = value;
    }

    /**
     * Gets the value of the unidadeQuantidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnidadeQuantidade() {
        return unidadeQuantidade;
    }

    /**
     * Sets the value of the unidadeQuantidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnidadeQuantidade(String value) {
        this.unidadeQuantidade = value;
    }

    /**
     * Gets the value of the valorIntervaloTempo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorIntervaloTempo() {
        return valorIntervaloTempo;
    }

    /**
     * Sets the value of the valorIntervaloTempo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorIntervaloTempo(BigDecimal value) {
        this.valorIntervaloTempo = value;
    }

}
