//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 08:27:36 PM UTC 
//


package inteli.sudeste;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}codigoCategoria"/&gt;
 *         &lt;element ref="{}codigoExportador" minOccurs="0"/&gt;
 *         &lt;element ref="{}codigoSubCategoria"/&gt;
 *         &lt;element ref="{}descricao"/&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}idSistemaProdutivo" minOccurs="0"/&gt;
 *         &lt;element ref="{}indicadorCFR"/&gt;
 *         &lt;element ref="{}indicadorFOB"/&gt;
 *         &lt;element ref="{}indicadorOrigem"/&gt;
 *         &lt;element ref="{}pesoMaximoPilha" minOccurs="0"/&gt;
 *         &lt;element ref="{}pesoMinimoPilha" minOccurs="0"/&gt;
 *         &lt;element ref="{}projetado"/&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element ref="{}restricaoIndicadorCFR"/&gt;
 *           &lt;element ref="{}restricaoIndicadorFOB"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element ref="{}tipoProduto"/&gt;
 *         &lt;element ref="{}unidadeFederativa" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoCategoria",
    "codigoExportador",
    "codigoSubCategoria",
    "descricao",
    "id",
    "idSistemaProdutivo",
    "indicadorCFR",
    "indicadorFOB",
    "indicadorOrigem",
    "pesoMaximoPilha",
    "pesoMinimoPilha",
    "projetado",
    "restricaoIndicadorCFR",
    "restricaoIndicadorFOB",
    "tipoProduto",
    "unidadeFederativa"
})
@XmlRootElement(name = "produtoAPS")
public class ProdutoAPS {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoCategoria;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoExportador;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoSubCategoria;
    @XmlElement(required = true)
    protected String descricao;
    @XmlElement(required = true)
    protected Id id;
    protected BigInteger idSistemaProdutivo;
    protected boolean indicadorCFR;
    protected boolean indicadorFOB;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String indicadorOrigem;
    protected BigDecimal pesoMaximoPilha;
    protected BigDecimal pesoMinimoPilha;
    protected boolean projetado;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String restricaoIndicadorCFR;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String restricaoIndicadorFOB;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tipoProduto;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String unidadeFederativa;

    /**
     * Gets the value of the codigoCategoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCategoria() {
        return codigoCategoria;
    }

    /**
     * Sets the value of the codigoCategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCategoria(String value) {
        this.codigoCategoria = value;
    }

    /**
     * Gets the value of the codigoExportador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoExportador() {
        return codigoExportador;
    }

    /**
     * Sets the value of the codigoExportador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoExportador(String value) {
        this.codigoExportador = value;
    }

    /**
     * Gets the value of the codigoSubCategoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoSubCategoria() {
        return codigoSubCategoria;
    }

    /**
     * Sets the value of the codigoSubCategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoSubCategoria(String value) {
        this.codigoSubCategoria = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the idSistemaProdutivo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdSistemaProdutivo() {
        return idSistemaProdutivo;
    }

    /**
     * Sets the value of the idSistemaProdutivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdSistemaProdutivo(BigInteger value) {
        this.idSistemaProdutivo = value;
    }

    /**
     * Gets the value of the indicadorCFR property.
     * 
     */
    public boolean isIndicadorCFR() {
        return indicadorCFR;
    }

    /**
     * Sets the value of the indicadorCFR property.
     * 
     */
    public void setIndicadorCFR(boolean value) {
        this.indicadorCFR = value;
    }

    /**
     * Gets the value of the indicadorFOB property.
     * 
     */
    public boolean isIndicadorFOB() {
        return indicadorFOB;
    }

    /**
     * Sets the value of the indicadorFOB property.
     * 
     */
    public void setIndicadorFOB(boolean value) {
        this.indicadorFOB = value;
    }

    /**
     * Gets the value of the indicadorOrigem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorOrigem() {
        return indicadorOrigem;
    }

    /**
     * Sets the value of the indicadorOrigem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorOrigem(String value) {
        this.indicadorOrigem = value;
    }

    /**
     * Gets the value of the pesoMaximoPilha property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPesoMaximoPilha() {
        return pesoMaximoPilha;
    }

    /**
     * Sets the value of the pesoMaximoPilha property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPesoMaximoPilha(BigDecimal value) {
        this.pesoMaximoPilha = value;
    }

    /**
     * Gets the value of the pesoMinimoPilha property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPesoMinimoPilha() {
        return pesoMinimoPilha;
    }

    /**
     * Sets the value of the pesoMinimoPilha property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPesoMinimoPilha(BigDecimal value) {
        this.pesoMinimoPilha = value;
    }

    /**
     * Gets the value of the projetado property.
     * 
     */
    public boolean isProjetado() {
        return projetado;
    }

    /**
     * Sets the value of the projetado property.
     * 
     */
    public void setProjetado(boolean value) {
        this.projetado = value;
    }

    /**
     * Gets the value of the restricaoIndicadorCFR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestricaoIndicadorCFR() {
        return restricaoIndicadorCFR;
    }

    /**
     * Sets the value of the restricaoIndicadorCFR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestricaoIndicadorCFR(String value) {
        this.restricaoIndicadorCFR = value;
    }

    /**
     * Gets the value of the restricaoIndicadorFOB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestricaoIndicadorFOB() {
        return restricaoIndicadorFOB;
    }

    /**
     * Sets the value of the restricaoIndicadorFOB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestricaoIndicadorFOB(String value) {
        this.restricaoIndicadorFOB = value;
    }

    /**
     * Gets the value of the tipoProduto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoProduto() {
        return tipoProduto;
    }

    /**
     * Sets the value of the tipoProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoProduto(String value) {
        this.tipoProduto = value;
    }

    /**
     * Gets the value of the unidadeFederativa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnidadeFederativa() {
        return unidadeFederativa;
    }

    /**
     * Sets the value of the unidadeFederativa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnidadeFederativa(String value) {
        this.unidadeFederativa = value;
    }

}
