//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.22 at 08:27:36 PM UTC
//


package inteli.sudeste;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}alocacaoRestrita"/&gt;
 *         &lt;element ref="{}alocacaoTrimestral"/&gt;
 *         &lt;element ref="{}cenarioFechamentoPV"/&gt;
 *         &lt;element ref="{}cenarioPrevisaoVenda"/&gt;
 *         &lt;element ref="{}codigoSistemaProducao"/&gt;
 *         &lt;element ref="{}dataHoraCriacaoCenario"/&gt;
 *         &lt;element ref="{}dataHoraInstanteInicial"/&gt;
 *         &lt;element ref="{}dataHoraTerminoCriacaoCenario"/&gt;
 *         &lt;element ref="{}dataInicioVigenciaCenario"/&gt;
 *         &lt;element ref="{}dataTerminoVigenciaCenario"/&gt;
 *         &lt;element ref="{}enviarEmbarqueCPF"/&gt;
 *         &lt;element ref="{}fixarMovimentacoesInterSistemaGlobais"/&gt;
 *         &lt;element ref="{}indicadorCurtissimoPrazo"/&gt;
 *         &lt;element ref="{}indicadorCurtoPrazoAsia"/&gt;
 *         &lt;element ref="{}indicadorCurtoPrazoFuturo"/&gt;
 *         &lt;element ref="{}indicadorCurtoPrazo"/&gt;
 *         &lt;element ref="{}indicadorCurtoPrazoProgramacao"/&gt;
 *         &lt;element ref="{}indicadorLongoPrazo"/&gt;
 *         &lt;element ref="{}indicadorMedioPrazoGlobal"/&gt;
 *         &lt;element ref="{}indicadorMedioPrazoLocal"/&gt;
 *         &lt;element ref="{}indicadorMetaAlocacao"/&gt;
 *         &lt;element ref="{}indicadorPV"/&gt;
 *         &lt;element ref="{}indicadorReportAlocacao"/&gt;
 *         &lt;element ref="{}parametrosOtimizacao"/&gt;
 *         &lt;element ref="{}itensSistemasProducaoCenario"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alocacaoRestrita",
    "alocacaoTrimestral",
    "cenarioFechamentoPV",
    "cenarioPrevisaoVenda",
    "codigoSistemaProducao",
    "dataHoraCriacaoCenario",
    "dataHoraInstanteInicial",
    "dataHoraTerminoCriacaoCenario",
    "dataInicioVigenciaCenario",
    "dataTerminoVigenciaCenario",
    "enviarEmbarqueCPF",
    "fixarMovimentacoesInterSistemaGlobais",
    "indicadorCurtissimoPrazo",
    "indicadorCurtoPrazoAsia",
    "indicadorCurtoPrazoFuturo",
    "indicadorCurtoPrazo",
    "indicadorCurtoPrazoProgramacao",
    "indicadorLongoPrazo",
    "indicadorMedioPrazoGlobal",
    "indicadorMedioPrazoLocal",
    "indicadorMetaAlocacao",
    "indicadorPV",
    "indicadorReportAlocacao",
    "parametrosOtimizacao",
    "itensSistemasProducaoCenario"
})
@XmlRootElement(name = "propriedade")
public class Propriedade {

    protected boolean alocacaoRestrita;
    protected boolean alocacaoTrimestral;
    protected boolean cenarioFechamentoPV;
    protected boolean cenarioPrevisaoVenda;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoSistemaProducao;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataHoraCriacaoCenario;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataHoraInstanteInicial;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataHoraTerminoCriacaoCenario;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataInicioVigenciaCenario;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataTerminoVigenciaCenario;
    protected boolean enviarEmbarqueCPF;
    protected boolean fixarMovimentacoesInterSistemaGlobais;
    protected boolean indicadorCurtissimoPrazo;
    protected boolean indicadorCurtoPrazoAsia;
    protected boolean indicadorCurtoPrazoFuturo;
    protected boolean indicadorCurtoPrazo;
    protected boolean indicadorCurtoPrazoProgramacao;
    protected boolean indicadorLongoPrazo;
    protected boolean indicadorMedioPrazoGlobal;
    protected boolean indicadorMedioPrazoLocal;
    protected boolean indicadorMetaAlocacao;
    protected boolean indicadorPV;
    protected boolean indicadorReportAlocacao;
    @XmlElement(required = true)
    protected ParametrosOtimizacao parametrosOtimizacao;
    @XmlElement(required = true)
    protected ItensSistemasProducaoCenario itensSistemasProducaoCenario;

    /**
     * Gets the value of the alocacaoRestrita property.
     *
     */
    public boolean isAlocacaoRestrita() {
        return alocacaoRestrita;
    }

    /**
     * Sets the value of the alocacaoRestrita property.
     *
     */
    public void setAlocacaoRestrita(boolean value) {
        this.alocacaoRestrita = value;
    }

    /**
     * Gets the value of the alocacaoTrimestral property.
     *
     */
    public boolean isAlocacaoTrimestral() {
        return alocacaoTrimestral;
    }

    /**
     * Sets the value of the alocacaoTrimestral property.
     *
     */
    public void setAlocacaoTrimestral(boolean value) {
        this.alocacaoTrimestral = value;
    }

    /**
     * Gets the value of the cenarioFechamentoPV property.
     *
     */
    public boolean isCenarioFechamentoPV() {
        return cenarioFechamentoPV;
    }

    /**
     * Sets the value of the cenarioFechamentoPV property.
     *
     */
    public void setCenarioFechamentoPV(boolean value) {
        this.cenarioFechamentoPV = value;
    }

    /**
     * Gets the value of the cenarioPrevisaoVenda property.
     *
     */
    public boolean isCenarioPrevisaoVenda() {
        return cenarioPrevisaoVenda;
    }

    /**
     * Sets the value of the cenarioPrevisaoVenda property.
     *
     */
    public void setCenarioPrevisaoVenda(boolean value) {
        this.cenarioPrevisaoVenda = value;
    }

    /**
     * Gets the value of the codigoSistemaProducao property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoSistemaProducao() {
        return codigoSistemaProducao;
    }

    /**
     * Sets the value of the codigoSistemaProducao property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoSistemaProducao(String value) {
        this.codigoSistemaProducao = value;
    }

    /**
     * Gets the value of the dataHoraCriacaoCenario property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataHoraCriacaoCenario() {
        return dataHoraCriacaoCenario;
    }

    /**
     * Sets the value of the dataHoraCriacaoCenario property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataHoraCriacaoCenario(XMLGregorianCalendar value) {
        this.dataHoraCriacaoCenario = value;
    }

    /**
     * Gets the value of the dataHoraInstanteInicial property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataHoraInstanteInicial() {
        return dataHoraInstanteInicial;
    }

    /**
     * Sets the value of the dataHoraInstanteInicial property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataHoraInstanteInicial(XMLGregorianCalendar value) {
        this.dataHoraInstanteInicial = value;
    }

    /**
     * Gets the value of the dataHoraTerminoCriacaoCenario property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataHoraTerminoCriacaoCenario() {
        return dataHoraTerminoCriacaoCenario;
    }

    /**
     * Sets the value of the dataHoraTerminoCriacaoCenario property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataHoraTerminoCriacaoCenario(XMLGregorianCalendar value) {
        this.dataHoraTerminoCriacaoCenario = value;
    }

    /**
     * Gets the value of the dataInicioVigenciaCenario property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataInicioVigenciaCenario() {
        return dataInicioVigenciaCenario;
    }

    /**
     * Sets the value of the dataInicioVigenciaCenario property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataInicioVigenciaCenario(XMLGregorianCalendar value) {
        this.dataInicioVigenciaCenario = value;
    }

    /**
     * Gets the value of the dataTerminoVigenciaCenario property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataTerminoVigenciaCenario() {
        return dataTerminoVigenciaCenario;
    }

    /**
     * Sets the value of the dataTerminoVigenciaCenario property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataTerminoVigenciaCenario(XMLGregorianCalendar value) {
        this.dataTerminoVigenciaCenario = value;
    }

    /**
     * Gets the value of the enviarEmbarqueCPF property.
     *
     */
    public boolean isEnviarEmbarqueCPF() {
        return enviarEmbarqueCPF;
    }

    /**
     * Sets the value of the enviarEmbarqueCPF property.
     *
     */
    public void setEnviarEmbarqueCPF(boolean value) {
        this.enviarEmbarqueCPF = value;
    }

    /**
     * Gets the value of the fixarMovimentacoesInterSistemaGlobais property.
     *
     */
    public boolean isFixarMovimentacoesInterSistemaGlobais() {
        return fixarMovimentacoesInterSistemaGlobais;
    }

    /**
     * Sets the value of the fixarMovimentacoesInterSistemaGlobais property.
     *
     */
    public void setFixarMovimentacoesInterSistemaGlobais(boolean value) {
        this.fixarMovimentacoesInterSistemaGlobais = value;
    }

    /**
     * Gets the value of the indicadorCurtissimoPrazo property.
     *
     */
    public boolean isIndicadorCurtissimoPrazo() {
        return indicadorCurtissimoPrazo;
    }

    /**
     * Sets the value of the indicadorCurtissimoPrazo property.
     *
     */
    public void setIndicadorCurtissimoPrazo(boolean value) {
        this.indicadorCurtissimoPrazo = value;
    }

    /**
     * Gets the value of the indicadorCurtoPrazoAsia property.
     *
     */
    public boolean isIndicadorCurtoPrazoAsia() {
        return indicadorCurtoPrazoAsia;
    }

    /**
     * Sets the value of the indicadorCurtoPrazoAsia property.
     *
     */
    public void setIndicadorCurtoPrazoAsia(boolean value) {
        this.indicadorCurtoPrazoAsia = value;
    }

    /**
     * Gets the value of the indicadorCurtoPrazoFuturo property.
     *
     */
    public boolean isIndicadorCurtoPrazoFuturo() {
        return indicadorCurtoPrazoFuturo;
    }

    /**
     * Sets the value of the indicadorCurtoPrazoFuturo property.
     *
     */
    public void setIndicadorCurtoPrazoFuturo(boolean value) {
        this.indicadorCurtoPrazoFuturo = value;
    }

    /**
     * Gets the value of the indicadorCurtoPrazo property.
     *
     */
    public boolean isIndicadorCurtoPrazo() {
        return indicadorCurtoPrazo;
    }

    /**
     * Sets the value of the indicadorCurtoPrazo property.
     *
     */
    public void setIndicadorCurtoPrazo(boolean value) {
        this.indicadorCurtoPrazo = value;
    }

    /**
     * Gets the value of the indicadorCurtoPrazoProgramacao property.
     *
     */
    public boolean isIndicadorCurtoPrazoProgramacao() {
        return indicadorCurtoPrazoProgramacao;
    }

    /**
     * Sets the value of the indicadorCurtoPrazoProgramacao property.
     *
     */
    public void setIndicadorCurtoPrazoProgramacao(boolean value) {
        this.indicadorCurtoPrazoProgramacao = value;
    }

    /**
     * Gets the value of the indicadorLongoPrazo property.
     *
     */
    public boolean isIndicadorLongoPrazo() {
        return indicadorLongoPrazo;
    }

    /**
     * Sets the value of the indicadorLongoPrazo property.
     *
     */
    public void setIndicadorLongoPrazo(boolean value) {
        this.indicadorLongoPrazo = value;
    }

    /**
     * Gets the value of the indicadorMedioPrazoGlobal property.
     *
     */
    public boolean isIndicadorMedioPrazoGlobal() {
        return indicadorMedioPrazoGlobal;
    }

    /**
     * Sets the value of the indicadorMedioPrazoGlobal property.
     *
     */
    public void setIndicadorMedioPrazoGlobal(boolean value) {
        this.indicadorMedioPrazoGlobal = value;
    }

    /**
     * Gets the value of the indicadorMedioPrazoLocal property.
     *
     */
    public boolean isIndicadorMedioPrazoLocal() {
        return indicadorMedioPrazoLocal;
    }

    /**
     * Sets the value of the indicadorMedioPrazoLocal property.
     *
     */
    public void setIndicadorMedioPrazoLocal(boolean value) {
        this.indicadorMedioPrazoLocal = value;
    }

    /**
     * Gets the value of the indicadorMetaAlocacao property.
     *
     */
    public boolean isIndicadorMetaAlocacao() {
        return indicadorMetaAlocacao;
    }

    /**
     * Sets the value of the indicadorMetaAlocacao property.
     *
     */
    public void setIndicadorMetaAlocacao(boolean value) {
        this.indicadorMetaAlocacao = value;
    }

    /**
     * Gets the value of the indicadorPV property.
     *
     */
    public boolean isIndicadorPV() {
        return indicadorPV;
    }

    /**
     * Sets the value of the indicadorPV property.
     *
     */
    public void setIndicadorPV(boolean value) {
        this.indicadorPV = value;
    }

    /**
     * Gets the value of the indicadorReportAlocacao property.
     *
     */
    public boolean isIndicadorReportAlocacao() {
        return indicadorReportAlocacao;
    }

    /**
     * Sets the value of the indicadorReportAlocacao property.
     *
     */
    public void setIndicadorReportAlocacao(boolean value) {
        this.indicadorReportAlocacao = value;
    }

    /**
     * Gets the value of the parametrosOtimizacao property.
     *
     * @return
     *     possible object is
     *     {@link ParametrosOtimizacao }
     *
     */
    public ParametrosOtimizacao getParametrosOtimizacao() {
        return parametrosOtimizacao;
    }

    /**
     * Sets the value of the parametrosOtimizacao property.
     *
     * @param value
     *     allowed object is
     *     {@link ParametrosOtimizacao }
     *
     */
    public void setParametrosOtimizacao(ParametrosOtimizacao value) {
        this.parametrosOtimizacao = value;
    }

    /**
     * Gets the value of the itensSistemasProducaoCenario property.
     *
     * @return
     *     possible object is
     *     {@link ItensSistemasProducaoCenario }
     *
     */
    public ItensSistemasProducaoCenario getItensSistemasProducaoCenario() {
        return itensSistemasProducaoCenario;
    }

    /**
     * Sets the value of the itensSistemasProducaoCenario property.
     *
     * @param value
     *     allowed object is
     *     {@link ItensSistemasProducaoCenario }
     *
     */
    public void setItensSistemasProducaoCenario(ItensSistemasProducaoCenario value) {
        this.itensSistemasProducaoCenario = value;
    }

}
