//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.22 at 08:27:36 PM UTC
//


package inteli.sudeste;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}indicadorFator" minOccurs="0"/&gt;
 *         &lt;element ref="{}teorGrandeza"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "indicadorFator",
    "teorGrandeza"
})
@XmlRootElement(name = "qualidadeProdutoElo")
public class QualidadeProdutoElo {

    @XmlElement(required = true)
    protected Id id;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String indicadorFator;
    protected double teorGrandeza;

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link Id }
     *
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link Id }
     *
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the indicadorFator property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIndicadorFator() {
        return indicadorFator;
    }

    /**
     * Sets the value of the indicadorFator property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIndicadorFator(String value) {
        this.indicadorFator = value;
    }

    /**
     * Gets the value of the teorGrandeza property.
     *
     */
    public double getTeorGrandeza() {
        return teorGrandeza;
    }

    /**
     * Sets the value of the teorGrandeza property.
     *
     */
    public void setTeorGrandeza(double value) {
        this.teorGrandeza = value;
    }

}
