//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.22 at 08:27:36 PM UTC
//


package inteli.sudeste;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}codigoProduto"/&gt;
 *         &lt;element ref="{}dataInicioVigencia"/&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}idEloCadeiaProducao"/&gt;
 *         &lt;element ref="{}tipoAssociacao"/&gt;
 *         &lt;element ref="{}tipoCusto" minOccurs="0"/&gt;
 *         &lt;element ref="{}tipoEntrega"/&gt;
 *         &lt;element ref="{}tipoOcorrencia"/&gt;
 *         &lt;element ref="{}unidade"/&gt;
 *         &lt;element ref="{}utilizarCustoProducao"/&gt;
 *         &lt;element ref="{}valor"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoProduto",
    "dataInicioVigencia",
    "id",
    "idEloCadeiaProducao",
    "tipoAssociacao",
    "tipoCusto",
    "tipoEntrega",
    "tipoOcorrencia",
    "unidade",
    "utilizarCustoProducao",
    "valor"
})
@XmlRootElement(name = "receitaCusto")
public class ReceitaCusto {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoProduto;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataInicioVigencia;
    @XmlElement(required = true)
    protected Id id;
    @XmlElement(required = true)
    protected BigInteger idEloCadeiaProducao;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tipoAssociacao;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tipoCusto;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tipoEntrega;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tipoOcorrencia;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String unidade;
    protected boolean utilizarCustoProducao;
    @XmlElement(required = true)
    protected String valor;

    /**
     * Gets the value of the codigoProduto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoProduto() {
        return codigoProduto;
    }

    /**
     * Sets the value of the codigoProduto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoProduto(String value) {
        this.codigoProduto = value;
    }

    /**
     * Gets the value of the dataInicioVigencia property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataInicioVigencia() {
        return dataInicioVigencia;
    }

    /**
     * Sets the value of the dataInicioVigencia property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataInicioVigencia(XMLGregorianCalendar value) {
        this.dataInicioVigencia = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link Id }
     *
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link Id }
     *
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the idEloCadeiaProducao property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getIdEloCadeiaProducao() {
        return idEloCadeiaProducao;
    }

    /**
     * Sets the value of the idEloCadeiaProducao property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setIdEloCadeiaProducao(BigInteger value) {
        this.idEloCadeiaProducao = value;
    }

    /**
     * Gets the value of the tipoAssociacao property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTipoAssociacao() {
        return tipoAssociacao;
    }

    /**
     * Sets the value of the tipoAssociacao property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipoAssociacao(String value) {
        this.tipoAssociacao = value;
    }

    /**
     * Gets the value of the tipoCusto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTipoCusto() {
        return tipoCusto;
    }

    /**
     * Sets the value of the tipoCusto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipoCusto(String value) {
        this.tipoCusto = value;
    }

    /**
     * Gets the value of the tipoEntrega property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTipoEntrega() {
        return tipoEntrega;
    }

    /**
     * Sets the value of the tipoEntrega property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipoEntrega(String value) {
        this.tipoEntrega = value;
    }

    /**
     * Gets the value of the tipoOcorrencia property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTipoOcorrencia() {
        return tipoOcorrencia;
    }

    /**
     * Sets the value of the tipoOcorrencia property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipoOcorrencia(String value) {
        this.tipoOcorrencia = value;
    }

    /**
     * Gets the value of the unidade property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUnidade() {
        return unidade;
    }

    /**
     * Sets the value of the unidade property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUnidade(String value) {
        this.unidade = value;
    }

    /**
     * Gets the value of the utilizarCustoProducao property.
     *
     */
    public boolean isUtilizarCustoProducao() {
        return utilizarCustoProducao;
    }

    /**
     * Sets the value of the utilizarCustoProducao property.
     *
     */
    public void setUtilizarCustoProducao(boolean value) {
        this.utilizarCustoProducao = value;
    }

    /**
     * Gets the value of the valor property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValor() {
        return valor;
    }

    /**
     * Sets the value of the valor property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValor(String value) {
        this.valor = value;
    }

}
