//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 08:27:36 PM UTC 
//


package inteli.sudeste;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}codHorizonte" minOccurs="0"/&gt;
 *         &lt;element ref="{}codProdutoFeed"/&gt;
 *         &lt;element ref="{}codProdutoPelota"/&gt;
 *         &lt;element ref="{}codProdutoPrimario" minOccurs="0"/&gt;
 *         &lt;element ref="{}dataInicioVigencia"/&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}idElo"/&gt;
 *         &lt;element ref="{}indiceConsumoEspecifico"/&gt;
 *         &lt;element ref="{}indiceConsumoEspecificoLegado" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codHorizonte",
    "codProdutoFeed",
    "codProdutoPelota",
    "codProdutoPrimario",
    "dataInicioVigencia",
    "id",
    "idElo",
    "indiceConsumoEspecifico",
    "indiceConsumoEspecificoLegado"
})
@XmlRootElement(name = "regraTransformacaoUsina")
public class RegraTransformacaoUsina {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codHorizonte;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codProdutoFeed;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codProdutoPelota;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codProdutoPrimario;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataInicioVigencia;
    @XmlElement(required = true)
    protected Id id;
    @XmlElement(required = true)
    protected BigInteger idElo;
    @XmlElement(required = true)
    protected BigDecimal indiceConsumoEspecifico;
    protected BigDecimal indiceConsumoEspecificoLegado;

    /**
     * Gets the value of the codHorizonte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodHorizonte() {
        return codHorizonte;
    }

    /**
     * Sets the value of the codHorizonte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodHorizonte(String value) {
        this.codHorizonte = value;
    }

    /**
     * Gets the value of the codProdutoFeed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProdutoFeed() {
        return codProdutoFeed;
    }

    /**
     * Sets the value of the codProdutoFeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProdutoFeed(String value) {
        this.codProdutoFeed = value;
    }

    /**
     * Gets the value of the codProdutoPelota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProdutoPelota() {
        return codProdutoPelota;
    }

    /**
     * Sets the value of the codProdutoPelota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProdutoPelota(String value) {
        this.codProdutoPelota = value;
    }

    /**
     * Gets the value of the codProdutoPrimario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProdutoPrimario() {
        return codProdutoPrimario;
    }

    /**
     * Sets the value of the codProdutoPrimario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProdutoPrimario(String value) {
        this.codProdutoPrimario = value;
    }

    /**
     * Gets the value of the dataInicioVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataInicioVigencia() {
        return dataInicioVigencia;
    }

    /**
     * Sets the value of the dataInicioVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataInicioVigencia(XMLGregorianCalendar value) {
        this.dataInicioVigencia = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the idElo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdElo() {
        return idElo;
    }

    /**
     * Sets the value of the idElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdElo(BigInteger value) {
        this.idElo = value;
    }

    /**
     * Gets the value of the indiceConsumoEspecifico property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIndiceConsumoEspecifico() {
        return indiceConsumoEspecifico;
    }

    /**
     * Sets the value of the indiceConsumoEspecifico property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIndiceConsumoEspecifico(BigDecimal value) {
        this.indiceConsumoEspecifico = value;
    }

    /**
     * Gets the value of the indiceConsumoEspecificoLegado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIndiceConsumoEspecificoLegado() {
        return indiceConsumoEspecificoLegado;
    }

    /**
     * Sets the value of the indiceConsumoEspecificoLegado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIndiceConsumoEspecificoLegado(BigDecimal value) {
        this.indiceConsumoEspecificoLegado = value;
    }

}
