//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.22 at 08:27:36 PM UTC
//


package inteli.sudeste;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element ref="{}codigoCategoriaProduto"/&gt;
 *           &lt;element ref="{}codigoProdutoFinal"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}codigoProduto" minOccurs="0"/&gt;
 *         &lt;element ref="{}codigoSubModal" minOccurs="0"/&gt;
 *         &lt;element ref="{}codigoTipoModal" minOccurs="0"/&gt;
 *         &lt;element ref="{}dataFimVigencia" minOccurs="0"/&gt;
 *         &lt;element ref="{}dataInicioVigencia"/&gt;
 *         &lt;element ref="{}habilitarRestricao"/&gt;
 *         &lt;element ref="{}id"/&gt;
 *         &lt;element ref="{}idEloCadeiaProducao"/&gt;
 *         &lt;element ref="{}idEloCadeiaProducaoDestinoDescarga" minOccurs="0"/&gt;
 *         &lt;element ref="{}indicadorUnidadeQuantidade"/&gt;
 *         &lt;element ref="{}indicadorUnidadeTempoTaxaDescargaExpedicao"/&gt;
 *         &lt;element ref="{}textoObservacao" minOccurs="0"/&gt;
 *         &lt;element ref="{}tipoOperacao"/&gt;
 *         &lt;element ref="{}tipoVisaoPrazo"/&gt;
 *         &lt;element ref="{}valorTaxaDescargaExpedicao" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoCategoriaProduto",
    "codigoProdutoFinal",
    "codigoProduto",
    "codigoSubModal",
    "codigoTipoModal",
    "dataFimVigencia",
    "dataInicioVigencia",
    "habilitarRestricao",
    "id",
    "idEloCadeiaProducao",
    "idEloCadeiaProducaoDestinoDescarga",
    "indicadorUnidadeQuantidade",
    "indicadorUnidadeTempoTaxaDescargaExpedicao",
    "textoObservacao",
    "tipoOperacao",
    "tipoVisaoPrazo",
    "valorTaxaDescargaExpedicao"
})
@XmlRootElement(name = "taxaDescargaExpedicaoElo")
public class TaxaDescargaExpedicaoElo {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoCategoriaProduto;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoProdutoFinal;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoProduto;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoSubModal;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codigoTipoModal;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataFimVigencia;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataInicioVigencia;
    protected boolean habilitarRestricao;
    @XmlElement(required = true)
    protected Id id;
    @XmlElement(required = true)
    protected BigInteger idEloCadeiaProducao;
    protected BigInteger idEloCadeiaProducaoDestinoDescarga;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String indicadorUnidadeQuantidade;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String indicadorUnidadeTempoTaxaDescargaExpedicao;
    protected String textoObservacao;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tipoOperacao;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tipoVisaoPrazo;
    protected BigDecimal valorTaxaDescargaExpedicao;

    /**
     * Gets the value of the codigoCategoriaProduto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoCategoriaProduto() {
        return codigoCategoriaProduto;
    }

    /**
     * Sets the value of the codigoCategoriaProduto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoCategoriaProduto(String value) {
        this.codigoCategoriaProduto = value;
    }

    /**
     * Gets the value of the codigoProdutoFinal property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoProdutoFinal() {
        return codigoProdutoFinal;
    }

    /**
     * Sets the value of the codigoProdutoFinal property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoProdutoFinal(String value) {
        this.codigoProdutoFinal = value;
    }

    /**
     * Gets the value of the codigoProduto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoProduto() {
        return codigoProduto;
    }

    /**
     * Sets the value of the codigoProduto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoProduto(String value) {
        this.codigoProduto = value;
    }

    /**
     * Gets the value of the codigoSubModal property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoSubModal() {
        return codigoSubModal;
    }

    /**
     * Sets the value of the codigoSubModal property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoSubModal(String value) {
        this.codigoSubModal = value;
    }

    /**
     * Gets the value of the codigoTipoModal property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoTipoModal() {
        return codigoTipoModal;
    }

    /**
     * Sets the value of the codigoTipoModal property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoTipoModal(String value) {
        this.codigoTipoModal = value;
    }

    /**
     * Gets the value of the dataFimVigencia property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataFimVigencia() {
        return dataFimVigencia;
    }

    /**
     * Sets the value of the dataFimVigencia property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataFimVigencia(XMLGregorianCalendar value) {
        this.dataFimVigencia = value;
    }

    /**
     * Gets the value of the dataInicioVigencia property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataInicioVigencia() {
        return dataInicioVigencia;
    }

    /**
     * Sets the value of the dataInicioVigencia property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataInicioVigencia(XMLGregorianCalendar value) {
        this.dataInicioVigencia = value;
    }

    /**
     * Gets the value of the habilitarRestricao property.
     *
     */
    public boolean isHabilitarRestricao() {
        return habilitarRestricao;
    }

    /**
     * Sets the value of the habilitarRestricao property.
     *
     */
    public void setHabilitarRestricao(boolean value) {
        this.habilitarRestricao = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link Id }
     *
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link Id }
     *
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the idEloCadeiaProducao property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getIdEloCadeiaProducao() {
        return idEloCadeiaProducao;
    }

    /**
     * Sets the value of the idEloCadeiaProducao property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setIdEloCadeiaProducao(BigInteger value) {
        this.idEloCadeiaProducao = value;
    }

    /**
     * Gets the value of the idEloCadeiaProducaoDestinoDescarga property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getIdEloCadeiaProducaoDestinoDescarga() {
        return idEloCadeiaProducaoDestinoDescarga;
    }

    /**
     * Sets the value of the idEloCadeiaProducaoDestinoDescarga property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setIdEloCadeiaProducaoDestinoDescarga(BigInteger value) {
        this.idEloCadeiaProducaoDestinoDescarga = value;
    }

    /**
     * Gets the value of the indicadorUnidadeQuantidade property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIndicadorUnidadeQuantidade() {
        return indicadorUnidadeQuantidade;
    }

    /**
     * Sets the value of the indicadorUnidadeQuantidade property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIndicadorUnidadeQuantidade(String value) {
        this.indicadorUnidadeQuantidade = value;
    }

    /**
     * Gets the value of the indicadorUnidadeTempoTaxaDescargaExpedicao property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIndicadorUnidadeTempoTaxaDescargaExpedicao() {
        return indicadorUnidadeTempoTaxaDescargaExpedicao;
    }

    /**
     * Sets the value of the indicadorUnidadeTempoTaxaDescargaExpedicao property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIndicadorUnidadeTempoTaxaDescargaExpedicao(String value) {
        this.indicadorUnidadeTempoTaxaDescargaExpedicao = value;
    }

    /**
     * Gets the value of the textoObservacao property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTextoObservacao() {
        return textoObservacao;
    }

    /**
     * Sets the value of the textoObservacao property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTextoObservacao(String value) {
        this.textoObservacao = value;
    }

    /**
     * Gets the value of the tipoOperacao property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTipoOperacao() {
        return tipoOperacao;
    }

    /**
     * Sets the value of the tipoOperacao property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipoOperacao(String value) {
        this.tipoOperacao = value;
    }

    /**
     * Gets the value of the tipoVisaoPrazo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTipoVisaoPrazo() {
        return tipoVisaoPrazo;
    }

    /**
     * Sets the value of the tipoVisaoPrazo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipoVisaoPrazo(String value) {
        this.tipoVisaoPrazo = value;
    }

    /**
     * Gets the value of the valorTaxaDescargaExpedicao property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getValorTaxaDescargaExpedicao() {
        return valorTaxaDescargaExpedicao;
    }

    /**
     * Sets the value of the valorTaxaDescargaExpedicao property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setValorTaxaDescargaExpedicao(BigDecimal value) {
        this.valorTaxaDescargaExpedicao = value;
    }

}
